<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language [
<!ELEMENT language (info+ , text+)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ATTLIST info id ID #IMPLIED>
<!ATTLIST text id ID #IMPLIED>
]>
<language>
  <info id="name">Deutsch</info>
  <info id="alias">de</info>
  <text id="ttAccountActivation">Kontoaktivierung</text>
  <text id="ttActive">Aktiv</text>
  <text id="ttActivate">Aktivieren</text>
  <text id="ttAdd">Hinzufügen</text>
  <text id="ttAddSelectedStudents">Ausgewählte Studenten hinzufügen</text>
  <text id="ttAdministration">Administration</text>
  <text id="ttAdministrator">Administrator</text>
  <text id="ttAdminWelcome">Willkommen zur Administrationsoberfläche.\nDieses System beinhaltet:</text>
  <text id="ttAlias">ISO 639-1 Code</text>
  <text id="ttAndExit">und schliessen</text>
  <text id="ttAnswer">Antwort</text>
  <text id="ttAnswers">Antworten</text>
  <text id="ttArchive">Archivieren</text>
  <text id="ttArchived">Archiviert</text>
  <text id="ttAssignSubject">Subject zuordnen</text>
  <text id="ttAutomatic">Automatisch</text>
  <text id="ttAImportComplete">Fragen-Import wurde erfolgreich abgeschlossen</text>
  <!-- ======================== B ======================== -->
  <text id="ttBasedOn">Basiert auf</text>
  <text id="ttBlocked">Geblockt</text>
  <text id="ttBlock">Blocken</text>
  <text id="ttUnblock">Blockierung aufheben</text>
  <text id="ttBonus">Bonus</text>
  <!-- ======================== C ======================== -->
  <text id="ttCancel">Abbrechen</text>
  <text id="ttChangeLanguage">Sprache ändern</text>
  <text id="ttChangeVersion">Test Version ändern</text>
  <text id="ttCheck">Testen...</text>
  <text id="ttClose">Schliessen</text>
  <text id="ttClosed">Geschlossen</text>
  <text id="ttCorrect">Korrekt</text>
  <text id="ttConfiguration">Konfiguration</text>
  <text id="ttConfirm">Bestätigen</text>
  <text id="ttConfirmEmail">Email bestätigen</text>
  <text id="ttConfirmPassword">Passwort bestätigen</text>
  <text id="ttCreate">Anlegen</text>
  <!-- ==================== CONFIRMS ===================== -->
  <text id="ttCArchiveExam">Wollen sie das Exam archivieren?\nAlle gestarteten Tests können nicht mehr beendet werden and all questions to correct of already submitted tests sum total of 0 points.\nDie Operation kann nicht rückgängig gemacht werden! Fortsetzen?</text>
  <text id="ttCBlockTest">Wollen sie diesen Test wirklich blockieren?</text>
  <text id="ttCChangeStatus">Wollen sie den Status der Frage wirklich ändern auf _STATUS_?</text>
  <text id="ttCConfirmTest">Wollen sie das Testergebnis bestätigen?\nDieser Test wird archiviert!\nFortsetzen?</text>
  <text id="ttCDeleteAnswer">Wollen sie diese Antwort und ihre Übersetzungen wirklich löschen?\nDieser Schritt kann nicht rückgängig gemacht werden!\nFortsetzen?</text>
  <text id="ttCDeleteExam">Wollen sie dieses Exam wirklich löschen?\nAlle laufenden, beendeten und archivierten Tests werden gelöscht.\nDieser Schritt kann nicht rückgängig gemacht werden!\nFortsetzen?</text>
  <text id="ttCDeleteQuestion">Wollen sie diese Frage und deren Übersetzungen löschen?\nDieser Schritt kann nicht rückgängig gemacht werden!\nFortsetzen?</text>
  <text id="ttCDeleteRoom">Wollen sie diesen Raum löschen?\nDieser Schritt kann nicht rückgängig gemacht werden!\nFortsetzen?</text>
  <text id="ttCDeleteSubject">Wollen sie dieses Subjekt löschen?\nDie folgenden Elemente werden PERMANENT entfernt:\n - Subjekt\n - Alle Kapitel\n - Alle Fragen und Antworten mit ihren Übersetzungen\n - Alle Einstellungen\n - Alle aktiven und archivierten Exams und Tests\nDieser Schritt kann nicht rückgängig gemacht werden! Fortsetzen?</text>
  <text id="ttCDeleteSettings">Wollen sie diese Test-Einstellungen löschen? Dieser Schritt kann nicht rückgängig gemacht werden.\nFortsetzen?</text>
  <text id="ttCDeleteTopic">Wollen sie dieses Kapitel löschen?\nDie folgenden Elemente werden PEMANENT entfernt:\n - Kapitel\n - Alle Fragen mit ihren Übersetzungen\n - Alle Antworten mit ihren Übersetzungen\nDieser Schritt kann nicht rückgängig gemacht werden! Fortsetzen?</text>
  <text id="ttCDiscardEdits">Ihre Änderungen gehen verloren.\nExit?</text>
  <text id="ttCDiscardNew">Das erzeugte Element geht verloren.\nExit?</text>
  <text id="ttCRegister">Wollen sie sich wirklich zu diesem Exam registrieren?</text>
  <text id="ttCRegisterStudents">Wollen sie die ausgewählten Studierenden wirklich für das Exam registrieren?</text>
  <text id="ttCRenewPassword">Das Passwort des Exams wird geändert.\nDieser Schritt kann nicht rückgängig gemacht werden.\nFortsetzen?</text>
  <text id="ttCStartExam">Wollen sie das ausgewählte Exam aktivieren?</text>
  <text id="ttCStartTest">Wollen sie das Exam nun starten?\nEin Exam Passwort wird benötigt.</text>
  <text id="ttCStopExam">Wollen sie das ausgewählte Exam deaktivieren?</text>
  <text id="ttCSubmitTest">Wollen sie den Test absenden?\nDieser Schritt kann nicht rückgängig gemacht werden!\nFortsetzen?</text>
  <text id="ttCTest">Das Passwort ist richtig. Ihr Test ist nun vorbereitet und startet nach dem Klick!</text>
  <text id="ttCumLaudae">cum Laudae</text>
  <text id="ttCUnblockTest">Wollen sie die Blockade des Tests aufheben?</text>
  <text id="ttCUpdateConfigurations">Wollen sie die neuen Systemeinstellungen speichern?</text>
  <text id="ttCUpdateLanguage">Wollen sie die Spach-Dateien aktualisieren?\nDieser Schritt kann nicht rückgängig gemacht werden. Fortsetzen?</text>
  <!-- ======================== D ======================== -->
  <text id="ttD1">Einfach</text>
  <text id="ttD2">Mittel</text>
  <text id="ttD3">Schwer</text>
  <text id="ttDatabaseConfiguration">Datenbank Einstellungen</text>
  <text id="ttDay">Tag</text>
  <text id="ttDelete">Löschen</text>
  <text id="ttDescription">Beschreibung</text>
  <text id="ttDifficulty">Schwierigkeitsgrad</text>
  <text id="ttDifficultyQuestions">Fragen pro Schwierigkeitsgrad</text>
  <text id="ttDistribution">Verteilung</text>
  <text id="ttDo">Exam durchführen</text>
  <text id="ttDTAnswerInfo">Zeige _TOTAL_ Antworten</text>
  <text id="ttDTAnswerFiltered">(gefiltert von _MAX_ Antworten insgesamt)</text>
  <text id="ttDTAnswerEmpty">Keine Antworten vorhanden</text>
  <text id="ttDTExamInfo">_TOTAL_ Exams im Laufen</text>
  <text id="ttDTExamFiltered">(gefiltert von _MAX_ laufenden Exams insgesamt)</text>
  <text id="ttDTExamEmpty">Keine Exams vorhanden</text>
  <text id="ttDTQuestionInfo">Zeige _TOTAL_ Fragen</text>
  <text id="ttDTQuestionFiltered">(gefiltert von _MAX_ Fragen insgesamt)</text>
  <text id="ttDTQuestionEmpty">Keine Fragen vorhanden</text>
  <text id="ttDTRegisteredStudentInfo">Zeige _TOTAL_ registrierte Studierende</text>
  <text id="ttDTRegisteredStudentFiltered">(gefiltert von _MAX_ registerten Studierenden insgesamt)</text>
  <text id="ttDTRegisteredStudentEmpty">Keine registrierten Studierenden vorhanden</text>
  <text id="ttDTStudentsInfo">Zeige _TOTAL_ Studierende</text>
  <text id="ttDTStudentsFiltered">(gefiltert von _MAX_ Studierenden insgesamt)</text>
  <text id="ttDTStudentsEmpty">Keine Studenten vorhanden</text>
  <text id="ttDTTestInfo">Zeige _TOTAL_ Tests</text>
  <text id="ttDTTeacherInfo">Zeige _TOTAL_ Lehrer</text>
  <text id="ttDTTeacherFiltered">(gefiltert von _MAX_ Lehrern insgesamt)</text>
  <text id="ttDTTeacherEmpty">Kein Lehrer vorhanden</text>
  <text id="ttDTTestFiltered">(gefiltert von _MAX_ Tests insgesamt)</text>
  <text id="ttDTTestEmpty">Keine Tests vorhanden</text>
  <text id="ttDone">Exam dürchgeführt</text>
  <text id="ttDuration">Dauer</text>
  <!-- ======================== E ======================== -->
  <text id="ttEdit">Editieren</text>
  <text id="ttEditableScore">Editable Score</text>
  <text id="ttError">Fehler</text>
  <text id="ttEmail">E-mail</text>
  <text id="ttEnd">Ende</text>
  <text id="ttEverywhere">Überall</text>
  <text id="ttExam">Exam</text>
  <text id="ttExams">Exams</text>
  <text id="ttExit">Exit</text>
  <text id="ttExtra">Extra</text>
  <text id="ttExamsArchive">Archive</text>
  <text id="ttExamsInProgress">Exams im laufen</text>
  <text id="ttETeachers">Examinator</text>
  <text id="ttErrorquestion">Report Fehler</text>
  <!-- ===================== ERRORS ====================== -->
  <text id="ttEActivationFails">Aktivierung fehlgeschlagen!</text>
  <text id="ttEAlreadyRegistered">Der Studiernde ist bereits für dieses Exam registriert!</text>
  <text id="ttEAnswerInSet">Dieser Schritt kann nicht abgeschlossen werden. Die Antwort wird in Tests verwendet!</text>
  <text id="ttEAnswerNotFound">Antwort nicht gefunden</text>
  <text id="ttEAnswers">Ein Problem mit den Antworten ist aufgetreten.\nBitte kontaktieren die den Lehrer oder Administrator.</text>
  <text id="ttEDatabase">Datenbank Fehler!</text>
  <text id="ttEDates">Termine sind nicht richtig!</text>
  <text id="ttEEditRoomAll">Der Raum 'All' kann nicht editiert werden!</text>
  <text id="ttEEmailAlreadyRegistered">E-mail bereits registriert!</text>
  <text id="ttEEmailNotRegistered">E-mail nicht registriert!</text>
  <text id="ttEEmailNotValid">Die eingetippte email ist nicht gültig! Bitte geben sie eine korrekte E-mail-Adresse ein</text>
  <text id="ttEEmailsNotMatch">Die beiden E-mail-Adressen stimmen nicht überein!</text>
  <text id="ttEEmptyFields">Ein oder mehrere Felder sind leer!</text>
  <text id="ttEExamArchived">Dieser Schritt kann nicht abgeschlossen werden. Das Exam ist bereits archiviert!</text>
  <text id="ttEExamNotFound">Exam nicht gefunden!</text>
  <text id="ttEExamNotStarted">Sie können das Exam nicht starten. Es ist noch nicht aktiv!</text>
  <text id="ttEExamStarted">Dieser Schritt kann nicht abgeschlossen werden weil das Exam bereits gestartet ist!</text>
  <text id="ttEExamWaiting">Dieser Schritt kann nicht abgeschlossen werden weil das Exam noch nie gestartet wurde!</text>
  <text id="ttEExamsNotArchivedDeleteTopic">Dieser Schritt kann nicht abgeschlossen werden weil zumindest ein nicht archiviertes Exam Fragen aus diesem Kapitel beinhaltet!</text>
  <text id="ttEExamsNotArchivedEditTestSettings">Dieser Schritt kann nicht abgeschlossen werden weil diese Einstellungen bei zumindest einem nicht archivierten Exam verwendet werden.\nNur der Name und die Beschreibung werden aktualisiert. Fortsetzen?</text>
  <text id="ttEExamsNotArchivedDeleteTestSettings">Dieser Schritt kann nicht abgeschlossen werden weil diese Einstellungen zumindest bei einem nicht archivierten Exam verwendet werden!</text>
  <text id="ttEIncorrectField">Ein oder mehrere Felder sind nicht korrekt!</text>
  <text id="ttELogin">E-mail und/oder Passwort sind nicht korrekt!</text>
  <text id="ttEMainLanguageEmpty">Subject's Hauptsprache kann nicht leer sein!</text>
  <text id="ttEMandatoryQuestion">Dies ist eine verpflichtende Frage von '_TESTSETTING_' Test's Einstellung: sie können diese nicht löschen oder den Schwierigkeitsgrad ändern.</text>
  <text id="ttENotAuthorized">Ihr Browser ist nicht authorisiert.\nBitte kontaktieren sie den Lehrer oder den Administrator.</text>
  <text id="ttENoStudentsToRegister">Keine Studierenden zu registrieren!</text>
  <text id="ttENoTopicsForSubject">Kein Kapitel für dieses Subjekt!\nUm eine neue Frage anzulegen müssen sie zuerst zumindest ein Kapitel anlegen.</text>
  <text id="ttEOldPasswordWrong">Das Passwort ist nicht korrekt!</text>
  <text id="ttEPassword">Falsches Passwort!</text>
  <text id="ttEPasswordShort">Das Passwort ist zu kurz. Es muss zumindest 8 Zeichen lang sein!</text>
  <text id="ttEPasswordsNotMatch">Die beiden Passwörter stimmen nicht überein!</text>
  <text id="ttEQuestAnswPicker">Error during questions and answers picking.\nPlease contact your teacher!</text>
  <text id="ttEQuestionInSet">Dieser Schritt kann nicht abgeschlossen werden. Die Frage wird in manchen Tests verwendet!</text>
  <text id="ttEQuestionNotFound">Frage nicht gefunden!</text>
  <text id="ttEQuestionType">Typ der Frage ist nicht korrekt!</text>
  <text id="ttERegFailedQuestions">Registrierung fehlgeschlagen: zu wenige Fragen! Bitte kontaktieren sie den Lehrer.</text>
  <text id="ttERoomAllDelete">Der Raum 'All' kann nicht gelöscht werden!</text>
  <text id="ttERoomUsed">Dieser Schritt kann nicht abgeschlossen werden. Der Raum wird in manchen Exams verwendet!</text>
  <text id="ttESaveBeforeNew">Vor dem Anlegen eines neuen Items speichern sie bitte das gerade erzeugte.</text>
  <text id="ttESelectQuestionType">Sie müssen eine der verfügbaren Fragentypen auswählen!</text>
  <text id="ttESelectSubject">Sie müssen einers der Subjekte auswählen!</text>
  <text id="ttESelectTestSettings">Sie müssen eine Test-Einstellung auswählen!</text>
  <text id="ttESetNotFound">Fragen-Set nicht gefunden!</text>
  <text id="ttETestAlreadyArchived">Dieser Schritt kann nicht abgeschlossen werden. Dieser Test wurde bereits korrigiert und archiviert!</text>
  <text id="ttETestAlreadySubmitted">Dieser Schritt kann nicht abgeschlossen werden. Dieser Test wurde bereits abgesendet und/oder archiviert.</text>
  <text id="ttETestBlockedSubmitted">Dieser Schritt kann nicht abgeschlossen werden. Dieser Test wurde geblockt or wurde bereits abgesendet!</text>
  <text id="ttETestNotArchived">Dieser Schritt kann nicht abgeschlossen werden. Dieser Test wurde noch nicht archiviert!</text>
  <text id="ttETestNotFound">Test nicht gefunden!</text>
  <text id="ttETestsNotArchived">Einige Tests wurden nicht archiviert! Bitte korrigieren sie zuerst alle Tests.</text>
  <text id="ttETestSettingDeleteQuestion">Dieser Schritt kann nicht abgeschlossen werden. Diese Frage ist verpflichtend in den folgenden Test-Einstellungens:</text>
  <text id="ttETestSettingDeleteTopic">Dieser Schritt kann nicht abgeschlossen werden. Einige Fragen dieses Kapitels werden in den folgenden Test-Einstellungen verwendet:</text>
  <text id="ttETimeExpired">Die verfügbare Zeit ist abgelaufen!</text>
  <text id="ttETranslationExists">Die Übersetzung der gewählten Sprache existiert bereits!</text>
  <text id="ttEUserNotFound">Benutzer nicht gefunden!</text>
  <text id="ttEValues">Einige Werte sind nicht korrekt!</text>
  <!-- ======================== F ======================== -->
  <text id="ttFalse">Falsch</text>
  <text id="ttFinalScore">Endgültiges Ergebnis</text>
  <!-- ======================== G ======================== -->
  <text id="ttGeneralInformations">Allgemeine Informationen</text>
  <!-- ======================== H ======================== -->
  <text id="ttHours">Stunden</text>
  <text id="ttHome">Home</text>
  <text id="ttHomepage">Startseite</text>
  <text id="ttHost">Host</text>
  <!-- ======================= HELP ====================== -->
  <text id="ttHAnswPanel">Doppelklick um die ausgewählte Antwort zu bearbeiten</text>
  <text id="ttHQuestLanguagesPanel">Klicken um die Ünersetzung\nder ausgewählten Frage anzuzeigen</text>
  <text id="ttHQuestPanel">Einfacher Klick um die Frage auszuwählen und anzuzeigen, und Doppelklick um die Frage und Antworten zu bearbeiten. Doppelklick auf die Flagge um die Frage zu aktivieren oder deaktivieren</text>
  <text id="ttHQuestPreviewPanel">Die Antworten mit orangem Hintergrund sind nicht in die gewählte Sprache übersetzt</text>
  <text id="ttHQuestTopicPanel">Einfacher Klick um Fragen zu filtern und\nDoppelklick um das Kapitel zu bearbeiten</text>
  <!-- ======================== I ======================== -->
  <text id="ttInfo">Info</text>
  <text id="ttIPEnd">IPv4 Ende</text>
  <text id="ttIPStart">IPv4 Anfang</text>
  <text id="ttInactive">Inaktiv</text>
  <text id="ttImportQM">Import</text>
  <text id="ttImport">Import QM</text>
  <text id="ttImportComplete">Import der Fragen wurde erfolgreich abgeschlossen</text>
  <!-- ======================== J ======================== -->
  <text id="ttJoin">Beitreten</text>
  <!-- ======================== K ======================== -->
  <!-- ======================== L ======================== -->
  <text id="ttLanguage">Sprache</text>
  <text id="ttLanguages">Sprachen</text>
  <text id="ttLogin">Login</text>
  <text id="ttLogo">Logo</text>
  <text id="ttLoginOk">Erfolgreich eingeloggt!</text>
  <text id="ttLogout">LOGOUT</text>
  <!-- ======================== M ======================== -->
  <text id="ttMailLostPassword">Um ihr Zugangspasswort zurückzusetzen klicken sie bitte auf folgenden Link:\n\n_LINK_\n\nWenn sie keine Rücksetzung des Passwortes angefordert haben ignorieren sie bitte diese email.</text>
  <text id="ttMailCredentials">Lieber _USERNAME_,\nIhr Passwort für Konto _USEREMAIL_ wurde auf Ihre Anfrage zurückgesetzt\nDas LibreEOL Team.</text>
  <text id="ttMailNewTeacher">Willkommen zu _SYSTEMNAME_.\nUm ihren Zugang zu aktivieren klicken sie bitte auf folgenden Link und setzen sie ihr Zugangspasswort:</text>
  <text id="ttMainLanguage">Hauptsprache</text>
  <text id="ttManage">Manage</text>
  <text id="ttMandatory">Verpflichtend</text>
  <text id="ttManual">Manual</text>
  <text id="ttMinutes">Minuten</text>
  <text id="ttMyExams">Meine Exams</text>
  <text id="ttMySettings">Meine Einstellungen</text>
  <text id="ttMySubjects">Wähle Subjekt</text>
  <!-- ==================== MESSAGES ===================== -->
  <text id="ttMActivation">Passwort erfolgreich gesetzt.\nSie werden nun zur Startseite weitergeleitet</text>
  <text id="ttMAnswerDeleted">Antwort erfolgreich gelöscht</text>
  <text id="ttMConfigurationsUpdated">System-Einstellungen erfolgreich aktualisiert</text>
  <text id="ttMConfirm">Test erfolgreich bestätigt und archiviert</text>
  <text id="ttMUserCreated">Benutzer angelegt: eine email mit einem Link zum Abschliessen ihrer Registrierung wurde ihnen zugesendet.\nBitte kontrollieren sie auch ihren SPAM-Folder!</text>
  <text id="ttMEdit">Änderungen erfolgreich gespeichert</text>
  <text id="ttMExamArchived">Exam erfolgreich archiviert</text>
  <text id="ttMExamDeleted">Exam erfolgreich gelöscht</text>
  <text id="ttMExamStarted">Exam erfolgreich gestartet</text>
  <text id="ttMExamStopped">Exam erfolgreich gestoppt</text>
  <text id="ttMLanguageCreated">Übersetzung erfolgreich angelegt</text>
  <text id="ttMLanguageSaved">Übersetzung erfolgreich gespeichert</text>
  <text id="ttMLanguageUpdated">Übersetzung erfolgreich aktualisiert</text>
  <text id="ttMNewAnswer">Antwort erfolgreich angelegt</text>
  <text id="ttMNewQuestion">Frage erfolgreich angelegt</text>
  <text id="ttMNewRoom">Raum erfolgreich angelegt</text>
  <text id="ttMNewSettings">Test-Einstellungen erfolgreich angelegt</text>
  <text id="ttMNewSubject">Sujekt erfolgreich angelegt</text>
  <text id="ttMNewTopic">Kapitel erfolgreich angelegt</text>
  <text id="ttMPasswordRenewed">Passwort des Exams erfolgreich neu erstellt</text>
  <text id="ttMQuestionDeleted">Frage erfolgreich gelöscht</text>
  <text id="ttMRegistration">Sie haben sich erfolgreich zu diesem Exam registriert</text>
  <text id="ttMResetConfirmed">Request completed: eine Email wurde ihnen zugesendet um das Passwort neu zu setzen.\nBitte kontrollieren sie auch ihren Spam-Ordner</text>
  <text id="ttMRoomDeleted">Raum erfolgreich gelöscht</text>
  <text id="ttMSelectLanguage">Wählen sie die Sprache welche sie bearbeiten möchten</text>
  <text id="ttMSettingsDeleted">Test-Einstellungen erfolgreich gelöscht</text>
  <text id="ttMStudentsRegistered">Studierenden erfolgreich zum Exam registriert</text>
  <text id="ttMSubjectDeleted">Subjekt erfolgreich gelöscht</text>
  <text id="ttMSubjectQuestions">Um Kapitel und Fragen zu bearbeiten wählen sie bitte ein Subjekt</text>
  <text id="ttMSubjectSettings">Um Exam-Einstellungen zu bearbeiten wählen sie bitte ein Subjekt</text>
  <text id="ttMTestBlocked">Test erfolgreich geblockt</text>
  <text id="ttMTestSubmitted">Test erfolgreich abgesendet</text>
  <text id="ttMTestUnblocked">Test erfolgreich freigeschalten</text>
  <text id="ttMTopicDeleted">Kapitel erfolgreich gelöscht</text>
  <!-- ======================== N ======================== -->
  <text id="ttName">Name</text>
  <text id="ttNumberError">Der Wert soll ein Integer oder eine Dezimalzahl sein (zB: 12.5)</text>
  <text id="ttNegativeScores">Negative Wertung</text>
  <text id="ttNew">Neu</text>
  <text id="ttNext">Next</text>
  <text id="ttNewAnswer">Neue Antwort</text>
  <text id="ttNewCredentials">Neue Zugangsdaten</text>
  <text id="ttNewLanguage">Neue Sprache</text>
  <text id="ttNewPassword">Neues Passwort</text>
  <text id="ttNewQuestion">Neue Frage</text>
  <text id="ttNewRegistration">Neue Registrierung</text>
  <text id="ttNewRoom">Neuer Raum</text>
  <text id="ttNewTeacher">Neuer Lehrer</text>
  <text id="ttNewTestSettings">Neue Einstellungen</text>
  <text id="ttNewSubject">Neues Subjekt</text>
  <text id="ttNewStudent">Neuer Studierender</text>
  <text id="ttNewTopic">Neues Kapitel</text>
  <text id="ttNewUser">Neuer Benutzer</text>
  <text id="ttNo">Nein</text>
  <text id="ttNoAnswers">Keine Antworten verfügbar für diese Frage</text>
  <text id="ttNoExams">Kein Exam verfügbar für dieses Subjekt</text>
  <text id="ttNoExamInProgress">Kein Exam im laufen</text>
  <text id="ttNoInfo">Es gibt keine Informationen für dieses Exam</text>
  <text id="ttNoQuestions">Keine Fragen verfügbar für dieses Kapitel</text>
  <text id="ttNoRooms">Kein Raum angelegt: nur 'All' verfügbar</text>
  <text id="ttNoSettings">Keine Einstellungen verfügbar für dieses Subjekt</text>
  <text id="ttNoSubjects">Keine Subjekts verfügbar</text>
  <text id="ttNoTestToCorrect">Keine Tests zu korrigieren</text>
  <text id="ttNoUserRegistered">Keine registrierten Benutzer für dieses Exam verfügbar</text>
  <!-- ======================== O ======================== -->
  <text id="ttOldPassword">Altes Passwort</text>
  <text id="ttEssayQuestion">Aufsatz-Frage</text>
  <!-- ======================== P ======================== -->
  <text id="ttPassword">Passwort</text>
  <text id="ttPasswordLost">Passwort vergessen??</text>
  <text id="ttPort">Port</text>
  <text id="ttProfile">Profil</text>
  <text id="ttPrepareImportQM">Vorschau</text>
  <!-- ======================== Q ======================== -->
  <text id="ttQuestion">Frage</text>
  <text id="ttQuestionPreview">Vorschau der Frage</text>
  <text id="ttQuestions">Fragen</text>
  <text id="ttQEc">Rechner</text>
  <text id="ttQEp">Periodensystem</text>
  <text id="ttQTMC">Multiple Choice</text>
  <text id="ttQTMCDescription">Bei einer Multiple Choice-Frage wählt der Teilnehmer eine Antwort aus mehreren vorgegebenen Möglichkeiten aus um die Frage zu beantworten.</text>
  <text id="ttQTMR">Multiple Response</text>
  <text id="ttQTMRDescription">Eine Multiple Response-Frage ist ähnlich einer Multiple Choice-Frage, mit dem Unterschied dass mehr als eine der möglichen Antworten ausgewählt werden können.</text>
  <text id="ttQTES">Essay Question</text>
  <text id="ttQTESDescription">Eine Essay-Frage ermöglicht dem Teilnehmer einen längeren freien Text einzugeben um die Frage zu beantworten. Dieser Fragen-Typ kann auch dazu verwendet werden um Meinungen und Vorschläge zu einem beliebigen Thema abzufragen.</text>
  <text id="ttQTYN">Yes/No</text>
  <text id="ttQTYNDescription">Eine Yes/No-Frage ist eine Multiple Choice-Frage die der Teilnehmer mit "Ja" oder "Nein" beantworten muss.</text>
  <text id="ttQTTF">True/False</text>
  <text id="ttQTTFDescription">Eine True/False-Frage ist eine Multiple Choice-Frage die der Teilnehmer mit "Wahr" oder "Falsch" beantowrten muss.</text>
  <text id="ttQTNM">Numerc</text>
  <text id="ttQTNMDescription">Bei einer Numeric-Frage muss der Teilnehmer einen Zahlenwert als Antwort eingeben.</text>
  <text id="ttQTTM">Text Match</text>
  <text id="ttQTTMDescription">Bei einer Text Match-Frage gibt der Teilnehmer ein einzelnes Wort oder mehrere Wörter ein um die Frage zu beantworten. Sie bestimmen richtige oder falsche Wörter (oder Phrasen) durch Eingabe einer Liste von akzeptierten Antworten.</text>
  <text id="ttQTHS">Hotspot</text>
  <text id="ttQTHSDescription">Eine Hotspot-Frage ist eine Drag and Drop-Frage mit nur einem richtigen Bereich. Der Teilnehmer plaziert einen Marker auf das Bild um seine Antwort anzugeben.</text>
  <text id="ttQTPL">Pull Down List</text>
  <text id="ttQTPLDescription">descrizione Pull Down</text>
  <text id="ttQuestionsubPL">Unterfrage</text>
  <text id="ttQuesionid">Fragen ID</text>
  <text id="ttQuestionNotes">Beschreibung</text>
  <text id="ttQuestionsend">Sende Report</text>
  <text id="ttQuestionreporting">To report more questions you need to leave the id field blank</text>
  <!-- ======================== R ======================== -->
  <text id="ttRandom">Zufall</text>
  <text id="ttRefresh">Aktualisieren</text>
  <text id="ttRegister">Registrieren</text>
  <text id="ttRegistrations">Registrierungen</text>
  <text id="ttRegEnd">Registrierungsende</text>
  <text id="ttRenewPassword">Passwort erneuern</text>
  <text id="ttReset">Zurücksetzen</text>
  <text id="ttResetPassword">Passwort zurücksetzen</text>
  <text id="ttRole">Rolle</text>
  <text id="ttRooms">Räume</text>
  <!-- ======================== S ======================== -->
  <text id="ttSave">Speichern</text>
  <text id="ttSaveAnswerInfo">Save Answer Info</text>
  <text id="ttSaveLanguageFiles">Speichere Sprach-Dateien</text>
  <text id="ttSaveLanguageXML">Speichere XML-Sprach-Dateien</text>
  <text id="ttSaveQuestionInfo">Speichere Frageninformation</text>
  <text id="ttScore">Wertung</text>
  <text id="ttScoreFinal">Endgültige Wertung</text>
  <text id="ttScoreTest">Test-Wertung</text>
  <text id="ttScoreType">Score Type</text>
  <text id="ttScoreMin">minimale Wertung</text>
  <text id="ttSelectSubject">wähle Subjekt</text>
  <text id="ttSelectSubjectBefore">wähle zuerst ein Subjekt</text>
  <text id="ttSet">Set</text>
  <text id="ttSetPassword">Bitte setzen sie ihr Passwort</text>
  <text id="ttSettings">Einstellungen</text>
  <text id="ttShowHide">Anzeigen/Verstecken</text>
  <text id="ttSelectSubQuestion">Wählen sie eine Unterfrage</text>
  <text id="ttSkin">Skin</text>
  <text id="ttStart">Start</text>
  <text id="ttStarted">Gestartet</text>
  <text id="ttStop">Stopp</text>
  <text id="ttStopped">Gestoppt</text>
  <text id="ttStartTest">Test starten</text>
  <text id="ttStatus">Status</text>
  <text id="ttStats">Stats</text>
  <text id="ttStudent">Student</text>
  <text id="ttStudents">Studenten</text>
  <text id="ttST10">Tenths</text>
  <text id="ttST30">Thirtieths</text>
  <text id="ttST100">Hundredth</text>
  <text id="ttSubject">Subjekt</text>
  <text id="ttSubjects">Subjekte</text>
  <text id="ttSubmit">Absenden</text>
  <text id="ttSurname">Familienname</text>
  <text id="ttSystem">System</text>
  <text id="ttSystemConfiguration">System Einstellungen</text>
  <text id="ttSbjVers">Version</text>
  <!-- ======================== T ======================== -->
  <text id="ttTeacher">Lehrer</text>
  <text id="ttTeachers">Lehrer</text>
  <text id="ttTest">Test</text>
  <text id="ttTests">Tests</text>
  <text id="ttTestToCorrect">Tests zu korrigieren</text>
  <text id="ttText">Text</text>
  <text id="ttTime">Zeit</text>
  <text id="ttTimeEnd">Zeit Ende</text>
  <text id="ttTimeStart">Zeit Start</text>
  <text id="ttTimeUsed">Zeit verwendet</text>
  <text id="ttTimeZone">Zeitzone</text>
  <text id="ttTitle">Titel</text>
  <text id="ttTopic">Kapitel</text>
  <text id="ttTopics">Kapitel</text>
  <text id="ttTopicsAndQuestions">Kapitel und Fragen</text>
  <text id="ttTopicsQuestions">Fragen je Kapitel</text>
  <text id="ttTranslations">Übersetzungen</text>
  <text id="ttTrue">Wahr</text>
  <text id="ttType">Typ</text>
  <!-- ======================== U ======================== -->
  <text id="ttUser">Benutzer</text>
  <text id="ttUsers">Benutzer</text>
  <!-- ======================== V ======================== -->
  <text id="ttView">Ansicht</text>
  <!-- ======================== W ======================== -->
  <text id="ttWelcome">Willkommen</text>
  <text id="ttWaiting">Waiting</text>
  <text id="ttWarning">Warnung</text>
  <!-- ======================== X ======================== -->
  <!-- ======================== Y ======================== -->
  <text id="ttYes">Ja</text>
  <!-- ======================== Z ======================== -->
  <text id="ttDTsubquestionInfo">Unterfrage</text>
  <text id="ttAssesmentOverview">Assesment Übersichts Report</text>
  <text id="ttDeselectAll">alle abwählen</text>
  <text id="ttErrorUserParameter">Wählen sie die Details des Teilnehmers um fortzusetzen!</text>
  <text id="ttQuestionerror">Fragen ID</text>
  <text id="ttRemove">Entfernen</text>
  <text id="ttReport">Report</text>
  <text id="ttReportAOWelcome">Wählen sie ein Assessment und verwenden sie die Tabs des Wizards um Daten zu filtern</text>
  <text id="ttReportAOSelectAssesment">Wählen sie ein Assessment um einen Report zu erstellen</text>
  <text id="ttReportCoachingError">Wählen sie ein Assessment und einen Teilnehmer um forzusetzen</text>
  <text id="ttReportCoachingError2">Wählen sie ein Assessment um fortzusetzen</text>
  <text id="ttReportErrorStudent">Der ausgewählte Studierende hat nicht am gewählten Test teilgenommen</text>
  <text id="ttReportMainAO">Main</text>
  <text id="ttReportTemplateDeleteFailed">Löschen fehlgeschlagen</text>
  <text id="ttReportTemplateDelet">Template gelöscht</text>
  <text id="ttReportTemplateLoaded">Template caricato correttamente</text>
  <text id="ttReportTemplateSaveError">Geben sie einen Templatenamen ohne Leerzeichen ein!</text>
  <text id="ttReportTemplateSaved">Template korrekt gespeichert</text>
  <text id="ttReportTemplateDuplicateError">Templatename existiert bereits!</text>
  <text id="ttReportScoreFilter">Wenn sie bereits einen Teilnehmer ausgewählt haben wählen sie bitte nun einen neuen.</text>
  <text id="ttSelectAll">Alles auswählen</text>
  <text id="ttQTFB">Füllen sie die Lücken aus</text>
  <text id="ttQTFB_TEXT">Ergänzen sie den folgenedn Text mit den passenden Wörtern</text>