<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language [
<!ELEMENT language (info+ , text+)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ATTLIST info id ID #IMPLIED>
<!ATTLIST text id ID #IMPLIED>
]>
<language>
  <info id="name">Français</info>
  <info id="alias">fr</info>
  <!-- ======================== A ======================== -->
  <text id="ttAccountActivation">Activation de compte</text>
  <text id="ttActive">actif</text>
  <text id="ttActivate">Activer</text>
  <text id="ttAdd">Ajouter</text>
  <text id="ttAddSelectedStudents">Ajouter des étudiants sélectionnés</text>
  <text id="ttAdministration">Administration</text>
  <text id="ttAdministrator">Administrateur</text>
  <text id="ttAdminWelcome">Bienvenue dans le panneau d'administration.</text>
  <text id="ttAlias">Code ISO 639-1</text>
  <text id="ttAndExit">et sortie</text>
  <text id="ttAnswer">Réponse</text>
  <text id="ttAnswers">Réponses</text>
  <text id="ttArchive">Archiver</text>
  <text id="ttArchived">Archivé</text>
  <text id="ttAssignSubject">Attribuer un sujet</text>
  <text id="ttAutomatic">Automatique</text>
  <text id="ttAImportComplete">Questions Import déjà terminé avec succès</text>
  <!-- ======================== B ======================== -->
  <text id="ttBasedOn">Basé sur</text>
  <text id="ttBlocked">Bloqué</text>
  <text id="ttBlock">Bloc</text>
  <text id="ttUnblock">Débloquer</text>
  <text id="ttBonus">Prime</text>
  <!-- ======================== C ======================== -->
  <text id="ttCancel">Annuler</text>
  <text id="ttChangeLanguage">Changer de langue</text>
  <text id="ttChangeVersion">Changer la version de test</text>
  <text id="ttCheck">Vérifier...</text>
  <text id="ttClose">Fermer</text>
  <text id="ttClosed">Fermé</text>
  <text id="ttCorrect">Correct</text>
  <text id="ttConfiguration">Configuration</text>
  <text id="ttConfirm">Confirmer</text>
  <text id="ttConfirmEmail">Confirmez votre e-mail</text>
  <text id="ttConfirmPassword">Confirmez le mot de passe</text>
  <text id="ttCreate">Créer</text>
  <!-- ==================== CONFIRMS ===================== -->
  <text id="ttCArchiveExam">Êtes-vous sûr de vouloir archiver l'examen?</text>
  <text id="ttCBlockTest">Êtes-vous sûr de bloquer ce test?</text>
  <text id="ttCChangeStatus">Etes-vous sûr de changer le statut de la question en _STATUS_?</text>
  <text id="ttCConfirmTest">Voulez-vous confirmer le résultat du test?</text>
  <text id="ttCDeleteAnswer">Etes-vous sûr de vouloir supprimer cette réponse et ses traductions?</text>
  <text id="ttCDeleteExam">Êtes-vous sûr de vouloir supprimer cet examen?</text>
  <text id="ttCDeleteQuestion">Êtes-vous sûr de vouloir supprimer cette question et ses traductions?</text>
  <text id="ttCDeleteRoom">Êtes-vous sûr de vouloir supprimer cette pièce?</text>
  <text id="ttCDeleteSubject">Êtes-vous sûr de vouloir supprimer ce sujet?</text>
  <text id="ttCDeleteSettings">Êtes-vous sûr de vouloir supprimer ces paramètres de test?</text>
  <text id="ttCDeleteTopic">Êtes-vous sûr de vouloir supprimer ce sujet?</text>
  <text id="ttCDiscardEdits">Vos modifications seront perdues.</text>
  <text id="ttCDiscardNew">L'élément créé sera perdu.</text>
  <text id="ttCRegister">Êtes-vous sûr de vous inscrire à cet examen?</text>
  <text id="ttCRegisterStudents">Êtes-vous sûr d’inscrire ces étudiants sélectionnés à l’examen?</text>
  <text id="ttCRenewPassword">Le mot de passe de l'examen sera changé.</text>
  <text id="ttCStartExam">Voulez-vous activer l'examen sélectionné?</text>
  <text id="ttCStartTest">Voulez-vous commencer l'examen maintenant?</text>
  <text id="ttCStopExam">Voulez-vous désactiver l'examen sélectionné?</text>
  <text id="ttCSubmitTest">Voulez-vous soumettre votre test?</text>
  <text id="ttCTest">Le mot de passe est correct.</text>
  <text id="ttCumLaudae">cum Laudae</text>
  <text id="ttCUnblockTest">Êtes-vous sûr de débloquer ce test?</text>
  <text id="ttCUpdateConfigurations">Etes-vous sûr de sauvegarder les nouvelles configurations du système?</text>
  <text id="ttCUpdateLanguage">Êtes-vous sûr de mettre à jour les fichiers de langue?</text>
  <!-- ======================== D ======================== -->
  <text id="ttD1">Facile</text>
  <text id="ttD2">Moyen</text>
  <text id="ttD3">Difficile</text>
  <text id="ttDatabaseConfiguration">Configuration de la base de données</text>
  <text id="ttDay">journée</text>
  <text id="ttDelete">Effacer</text>
  <text id="ttDescription">La description</text>
  <text id="ttDifficulty">Difficulté</text>
  <text id="ttDifficultyQuestions">Questions par difficulté</text>
  <text id="ttDistribution">Distribution</text>
  <text id="ttDo">Faire l'examen</text>
  <text id="ttDTAnswerInfo">Affichage de _TOTAL_ réponses</text>
  <text id="ttDTAnswerFiltered">(filtré de _MAX_ réponses totales)</text>
  <text id="ttDTAnswerEmpty">Pas de réponse à montrer</text>
  <text id="ttDTExamInfo">Affichage des examens _TOTAL_ en cours</text>
  <text id="ttDTExamFiltered">(filtré de _MAX_ total des examens en cours)</text>
  <text id="ttDTExamEmpty">Aucun examen à afficher</text>
  <text id="ttDTQuestionInfo">Affichage de _TOTAL_ questions</text>
  <text id="ttDTQuestionFiltered">(filtré à partir de _MAX_ total de questions)</text>
  <text id="ttDTQuestionEmpty">Aucune question à afficher</text>
  <text id="ttDTRegisteredStudentInfo">Affichage de _TOTAL_ étudiants inscrits</text>
  <text id="ttDTRegisteredStudentFiltered">(filtré de _MAX_ total des étudiants inscrits)</text>
  <text id="ttDTRegisteredStudentEmpty">Aucun étudiant inscrit à montrer</text>
  <text id="ttDTStudentsInfo">Affichage de _TOTAL_ étudiants</text>
  <text id="ttDTStudentsFiltered">(filtré de _MAX_ total des étudiants)</text>
  <text id="ttDTStudentsEmpty">Aucun étudiant à montrer</text>
  <text id="ttDTTestInfo">Affichage de _TOTAL_ test</text>
  <text id="ttDTTeacherInfo">Affichage des enseignants _TOTAL_</text>
  <text id="ttDTTeacherFiltered">(filtré de _MAX_ total d'enseignants)</text>
  <text id="ttDTTeacherEmpty">Aucun enseignant à montrer</text>
  <text id="ttDTTestFiltered">(filtré à partir des tests _MAX_ total)</text>
  <text id="ttDTTestEmpty">Aucun test à montrer</text>
  <text id="ttDone">Examen fait</text>
  <text id="ttDuration">Durée</text>
  <text id="ttDTsubquestionInfo">Sous questions</text>
  <!-- ======================== E ======================== -->
  <text id="ttEdit">modifier</text>
  <text id="ttEditableScore">Partition éditable</text>
  <text id="ttError">Erreur</text>
  <text id="ttEmail">Email</text>
  <text id="ttEnd">Fin</text>
  <text id="ttEverywhere">Partout</text>
  <text id="ttExam">Examen</text>
  <text id="ttExams">Examens</text>
  <text id="ttExit">Sortie</text>
  <text id="ttExtra">Supplémentaire</text>
  <text id="ttExamsArchive">Archiver</text>
  <text id="ttExamsInProgress">Examens en cours</text>
  <text id="ttETeachers">Examinateur</text>
  <text id="ttErrorquestion">Signaler une erreur</text>
  <!-- ===================== ERRORS ====================== -->
  <text id="ttEActivationFails">L'activation échoue!</text>
  <text id="ttEAlreadyRegistered">L'étudiant est déjà inscrit à cet examen!</text>
  <text id="ttEAnswerInSet">L'opération ne peut pas être terminée.</text>
  <text id="ttEAnswerNotFound">Réponse non trouvée</text>
  <text id="ttEAnswers">Un problème de réponses s'est produit.</text>
  <text id="ttEDatabase">Erreur de la base de données!</text>
  <text id="ttEDates">Les dates ne sont pas correctes!</text>
  <text id="ttEEditRoomAll">La salle 'Toutes' ne peut pas être modifiée!</text>
  <text id="ttEEmailAlreadyRegistered">E-mail déjà enregistré!</text>
  <text id="ttEEmailNotRegistered">E-mail non enregistré!</text>
  <text id="ttEEmailNotValid">L'email tapé n'est pas valide!</text>
  <text id="ttEEmailsNotMatch">Les deux emails ne correspondent pas!</text>
  <text id="ttEEmptyFields">Un ou plusieurs champs sont vides!</text>
  <text id="ttEExamArchived">L'opération ne peut pas être terminée.</text>
  <text id="ttEExamNotFound">Examen non trouvé!</text>
  <text id="ttEExamNotStarted">Vous ne pouvez pas commencer l'examen.</text>
  <text id="ttEExamStarted">L'opération ne peut pas être terminée car l'examen est déjà commencé!</text>
  <text id="ttEExamWaiting">L'opération ne peut pas être terminée car l'examen n'est jamais commencé!</text>
  <text id="ttEExamsNotArchivedDeleteTopic">L'opération ne peut pas être terminée, car au moins un examen non archivé contient des questions de ce sujet!</text>
  <text id="ttEExamsNotArchivedEditTestSettings">L'opération ne peut pas être terminée car ces paramètres sont utilisés par au moins un examen non archivé.</text>
  <text id="ttEExamsNotArchivedDeleteTestSettings">L'opération ne peut pas être terminée car ces paramètres sont utilisés par au moins un examen non archivé!</text>
  <text id="ttEIncorrectField">Un ou plusieurs champs ne sont pas corrects!</text>
  <text id="ttELogin">E-mail et / ou mot de passe ne sont pas corrects!</text>
  <text id="ttEMainLanguageEmpty">La langue principale du sujet ne peut pas être vide!</text>
  <text id="ttEMandatoryQuestion">Ceci est une question obligatoire du paramétrage du test '_TESTSETTING_': vous ne pouvez pas le supprimer, ni modifier sa difficulté ou son sujet.</text>
  <text id="ttENotAuthorized">Votre client n'est pas autorisé.</text>
  <text id="ttENoStudentsToRegister">Aucun étudiant à s'inscrire!</text>
  <text id="ttENoTopicsForSubject">Pas de sujet pour ce sujet!</text>
  <text id="ttEOldPasswordWrong">L'ancien mot de passe n'est pas correct!</text>
  <text id="ttEPassword">Mauvais mot de passe!</text>
  <text id="ttEPasswordShort">Le mot de passe est trop court.</text>
  <text id="ttEPasswordsNotMatch">Les deux mots de passe ne correspondent pas!</text>
  <text id="ttEQuestAnswPicker">Erreur lors de la sélection des questions et réponses.</text>
  <text id="ttEQuestionInSet">L'opération ne peut pas être terminée.</text>
  <text id="ttEQuestionNotFound">Question non trouvée!</text>
  <text id="ttEQuestionType">Le type de question n'est pas correct!</text>
  <text id="ttERegFailedQuestions">L'inscription a échoué: trop peu de questions!</text>
  <text id="ttERoomAllDelete">La salle 'Toutes' ne peut pas être supprimée!</text>
  <text id="ttERoomUsed">L'opération ne peut pas être terminée.</text>
  <text id="ttESaveBeforeNew">Avant de créer un nouvel élément, veuillez enregistrer ou annuler celui déjà créé.</text>
  <text id="ttESelectQuestionType">Vous devez sélectionner l'un des types de questions disponibles!</text>
  <text id="ttESelectSubject">Vous devez sélectionner l'un de vos sujets!</text>
  <text id="ttESelectTestSettings">Vous devez sélectionner l'un des paramètres de test!</text>
  <text id="ttESetNotFound">Ensemble de questions non trouvé!</text>
  <text id="ttETestAlreadyArchived">L'opération ne peut pas être terminée.</text>
  <text id="ttETestAlreadySubmitted">L'opération ne peut pas être terminée.</text>
  <text id="ttETestBlockedSubmitted">L'opération ne peut pas être terminée.</text>
  <text id="ttETestNotArchived">L'opération ne peut pas être terminée.</text>
  <text id="ttETestNotFound">Test non trouvé!</text>
  <text id="ttETestsNotArchived">Certains tests n'ont pas été archivés!</text>
  <text id="ttETestSettingDeleteQuestion">L'opération ne peut pas être terminée.</text>
  <text id="ttETestSettingDeleteTopic">L'opération ne peut pas être terminée.</text>
  <text id="ttETimeExpired">Le temps disponible est expiré!</text>
  <text id="ttETranslationExists">La traduction de la langue sélectionnée existe déjà!</text>
  <text id="ttEUserNotFound">Utilisateur non trouvé!</text>
  <text id="ttEValues">Certaines valeurs ne sont pas correctes!</text>
  <!-- ======================== F ======================== -->
  <text id="ttFalse">Faux</text>
  <text id="ttFinalScore">Score final</text>
  <!-- ======================== G ======================== -->
  <text id="ttGeneralInformations">Informations générales</text>
  <!-- ======================== H ======================== -->
  <text id="ttHours">heures</text>
  <text id="ttHome">Accueil</text>
  <text id="ttHomepage">Page d'accueil</text>
  <text id="ttHost">Hôte</text>
  <!-- ======================= HELP ====================== -->
  <text id="ttHAnswPanel">Double-cliquez pour éditer la réponse sélectionnée</text>
  <text id="ttHQuestLanguagesPanel">Cliquez pour afficher la traduction de la question sélectionnée</text>
  <text id="ttHQuestPanel">Un simple clic pour sélectionner et afficher l'aperçu de la question, et double-cliquer pour modifier les informations sur la question et les réponses.</text>
  <text id="ttHQuestPreviewPanel">Les réponses sur fond orange ne sont pas traduites dans la langue demandée</text>
  <text id="ttHQuestTopicPanel">Un simple clic pour filtrer les questions et double-cliquer pour modifier les informations sur le sujet</text>
  <!-- ======================== I ======================== -->
  <text id="ttInfo">Info</text>
  <text id="ttIPEnd">Fin IPv4</text>
  <text id="ttIPStart">Début IPv4</text>
  <text id="ttInactive">Inactif</text>
  <text id="ttImportQM">Importation</text>
  <text id="ttImport">Importer QM</text>
  <text id="ttImportComplete">Questions importées avec succès</text>
  <!-- ======================== J ======================== -->
  <text id="ttJoin">Joindre</text>
  <!-- ======================== K ======================== -->
  <!-- ======================== L ======================== -->
  <text id="ttLanguage">La langue</text>
  <text id="ttLanguages">Les langues</text>
  <text id="ttLogin">S'identifier</text>
  <text id="ttLogo">Logo</text>
  <text id="ttLoginOk">Connexion terminée!</text>
  <text id="ttLogout">CONNECTEZ - OUT</text>
  <!-- ======================== M ======================== -->
  <text id="ttMailLostPassword">Pour réinitialiser le mot de passe de votre compte, cliquez sur le lien suivant: _LINK_ Si vous n'avez pas encore demandé de réinitialisation de mot de passe, ignorez cet e-mail.</text>
  <text id="ttMailCredentials">Cher _USERNAME_, Votre mot de passe associé au compte _USEREMAIL_ a été modifié en fonction de votre demande.</text>
  <text id="ttMailNewTeacher">Bienvenue sur _SYSTEMNAME_.</text>
  <text id="ttMainLanguage">Langage principal</text>
  <text id="ttManage">Gérer</text>
  <text id="ttMandatory">Obligatoire</text>
  <text id="ttManual">Manuel</text>
  <text id="ttMinutes">minutes</text>
  <text id="ttMyExams">Mes examens</text>
  <text id="ttMySettings">Mes paramètres</text>
  <text id="ttMySubjects">Sélectionnez un sujet</text>
  <!-- ==================== MESSAGES ===================== -->
  <text id="ttMActivation">Mot de passe défini avec succès.</text>
  <text id="ttMAnswerDeleted">Réponse supprimée avec succès</text>
  <text id="ttMConfigurationsUpdated">Configurations système mises à jour avec succès</text>
  <text id="ttMConfirm">Test confirmé et archivé avec succès</text>
  <text id="ttMUserCreated">Création terminée: un email vous a été envoyé pour compléter l'inscription.</text>
  <text id="ttMEdit">Edits sauvegardés avec succès</text>
  <text id="ttMExamArchived">Examen archivé avec succès</text>
  <text id="ttMExamDeleted">Examen supprimé avec succès</text>
  <text id="ttMExamStarted">Examen commencé avec succès</text>
  <text id="ttMExamStopped">Examen arrêté avec succès</text>
  <text id="ttMLanguageCreated">Traduction créée avec succès</text>
  <text id="ttMLanguageSaved">Traduction enregistrée avec succès</text>
  <text id="ttMLanguageUpdated">Traduction mise à jour avec succès</text>
  <text id="ttMNewAnswer">Réponse créée avec succès</text>
  <text id="ttMNewQuestion">Question créée avec succès</text>
  <text id="ttMNewRoom">Chambre créée avec succès</text>
  <text id="ttMNewSettings">Paramètres de test créés avec succès</text>
  <text id="ttMNewSubject">Sujet créé avec succès</text>
  <text id="ttMNewTopic">Sujet créé avec succès</text>
  <text id="ttMPasswordRenewed">Mot de passe de l'examen renouvelé avec succès</text>
  <text id="ttMQuestionDeleted">Question supprimée avec succès</text>
  <text id="ttMRegistration">Vous avez réussi votre inscription à cet examen</text>
  <text id="ttMResetConfirmed">Requête complétée: un email vous a été envoyé pour réinitialiser votre mot de passe.</text>
  <text id="ttMRoomDeleted">Chambre supprimée avec succès</text>
  <text id="ttMSelectLanguage">Sélectionnez la langue que vous souhaitez gérer</text>
  <text id="ttMSettingsDeleted">Paramètres de test supprimés avec succès</text>
  <text id="ttMStudentsRegistered">Etudiants inscrits à l'examen avec succès</text>
  <text id="ttMSubjectDeleted">Sujet supprimé avec succès</text>
  <text id="ttMSubjectQuestions">Pour gérer les sujets et les questions, sélectionnez le sujet.</text>
  <text id="ttMSubjectSettings">Pour gérer les paramètres de l'examen, veuillez sélectionner le sujet.</text>
  <text id="ttMTestBlocked">Test bloqué avec succès</text>
  <text id="ttMTestSubmitted">Test soumis avec succès</text>
  <text id="ttMTestUnblocked">Test débloqué avec succès</text>
  <text id="ttMTopicDeleted">Sujet supprimé avec succès</text>
  <!-- ======================== N ======================== -->
  <text id="ttName">prénom</text>
  <text id="ttNumberError">La valeur doit être un entier ou un nombre décimal (ES: 12.5)</text>
  <text id="ttNegativeScores">Scores négatifs</text>
  <text id="ttNew">Nouveau</text>
  <text id="ttNext">Suivant</text>
  <text id="ttNewAnswer">Nouvelle réponse</text>
  <text id="ttNewCredentials">Nouveaux pouvoirs</text>
  <text id="ttNewLanguage">Nouveau langage</text>
  <text id="ttNewPassword">nouveau mot de passe</text>
  <text id="ttNewQuestion">Nouvelle question</text>
  <text id="ttNewRegistration">Nouvelle inscription</text>
  <text id="ttNewRoom">Nouvelle pièce</text>
  <text id="ttNewTeacher">Nouveau professeur</text>
  <text id="ttNewTestSettings">Nouveaux paramètres</text>
  <text id="ttNewSubject">Nouveau sujet</text>
  <text id="ttNewStudent">Nouvel étudiant</text>
  <text id="ttNewTopic">Nouveau sujet</text>
  <text id="ttNewUser">Nouvel utilisateur</text>
  <text id="ttNo">Non</text>
  <text id="ttNoAnswers">Aucune réponse disponible pour cette question</text>
  <text id="ttNoExams">Aucun examen disponible pour ce sujet</text>
  <text id="ttNoExamInProgress">Aucun examen en cours</text>
  <text id="ttNoInfo">Il n'y a pas d'informations sur cet examen</text>
  <text id="ttNoQuestions">Aucune question disponible pour ce sujet</text>
  <text id="ttNoRooms">Aucune chambre créée: 'Tous' uniquement disponible</text>
  <text id="ttNoSettings">Aucun paramètre disponible pour ce sujet</text>
  <text id="ttNoSubjects">Aucun sujet disponible</text>
  <text id="ttNoTestToCorrect">Aucun test à corriger</text>
  <text id="ttNoUserRegistered">Aucun utilisateur enregistré pour cet examen</text>
  <!-- ======================== O ======================== -->
  <text id="ttOldPassword">ancien mot de passe</text>
  <text id="ttEssayQuestion">Question d'essai</text>
  <!-- ======================== P ======================== -->
  <text id="ttPassword">Mot de passe</text>
  <text id="ttPasswordLost">Mot de passe perdu?</text>
  <text id="ttPort">Port</text>
  <text id="ttProfile">Profil</text>
  <text id="ttPrepareImportQM">Aperçu</text>
  <!-- ======================== Q ======================== -->
  <text id="ttQuestion">Question</text>
  <text id="ttQuestionPreview">Aperçu de la question</text>
  <text id="ttQuestions">Des questions</text>
  <text id="ttQEc">Calculatrice</text>
  <text id="ttQEp">Tableau périodique</text>
  <text id="ttQTMC">Choix multiple</text>
  <text id="ttQTMCDescription">Dans une question à choix multiples, le participant sélectionne un seul choix parmi plusieurs choix pour répondre à la question.</text>
  <text id="ttQTMR">Réponse multiple</text>
  <text id="ttQTMRDescription">Une question à réponses multiples ressemble à un choix multiple, sauf qu'au lieu de devoir faire au plus un choix, l'utilisateur est autorisé à faire un ou plusieurs choix.</text>
  <text id="ttQTES">Question d'essai</text>
  <text id="ttQTESDescription">Une question de rédaction permet au participant de saisir une réponse textuelle longue et libre à une question.</text>
  <text id="ttQTYN">Oui Non</text>
  <text id="ttQTYNDescription">Une question Oui / Non est une question à choix multiples qui demande au participant de donner une réponse "Oui" ou "Non" à une question.</text>
  <text id="ttQTTF">Vrai faux</text>
  <text id="ttQTTFDescription">Une question Vrai / Faux est une question à choix multiples qui demande au participant de donner une réponse "Vrai" ou "Faux" à une question.</text>
  <text id="ttQTNM">Numérique</text>
  <text id="ttQTNMDescription">Dans une question numérique, le participant répond en saisissant un nombre entier ou un nombre réel.</text>
  <text id="ttQTTM">Correspondance de texte</text>
  <text id="ttQTTMDescription">In a Text Match question, the participant types in a single word, or a few words to indicate their answer. You define right or wrong words or phrases in advance by entering a list of acceptable answers.</text>
  <text id="ttQTHS">Hotspot</text>
  <text id="ttQTHSDescription">A Hotspot question is a drag and drop question with only one right area. The participant places a single marker on an image to indicate the answer.</text>
  <text id="ttQTPL">Pull Down List</text>
  <text id="ttQuesionid">Question ID</text>
  <text id="ttQuestionNotes">Description</text>
  <text id="ttQuestionsend">Send Report</text>
  <text id="ttQuestionreporting">To report more questions you need to leave the id field blank</text>
  <!-- ======================== R ======================== -->
  <text id="ttRandom">Random</text>
  <text id="ttRefresh">Refresh</text>
  <text id="ttRegister">Register</text>
  <text id="ttRegistrations">Registrations</text>
  <text id="ttRegEnd">Registation closure</text>
  <text id="ttRenewPassword">Renew Password</text>
  <text id="ttReset">Reset</text>
  <text id="ttResetPassword">Reset Password</text>
  <text id="ttRole">Role</text>
  <text id="ttRooms">Rooms</text>
  <!-- ======================== S ======================== -->
  <text id="ttSave">Save</text>
  <text id="ttSaveAnswerInfo">Save Answer Info</text>
  <text id="ttSaveLanguageFiles">Save Language Files</text>
  <text id="ttSaveLanguageXML">Enregistrer les fichiers de langue XML</text>
  <text id="ttSaveQuestionInfo">Enregistrer les informations sur la question</text>
  <text id="ttScore">But</text>
  <text id="ttScoreFinal">Score final</text>
  <text id="ttScoreTest">Score du test</text>
  <text id="ttScoreType">Type de score</text>
  <text id="ttScoreMin">Score minimum</text>
  <text id="ttSelectSubject">Sélectionnez un sujet</text>
  <text id="ttSelectSubjectBefore">Sélectionnez un sujet avant</text>
  <text id="ttSet">Ensemble</text>
  <text id="ttSetPassword">Veuillez définir votre mot de passe</text>
  <text id="ttSettings">Réglages</text>
  <text id="ttShowHide">Afficher / Masquer</text>
  <text id="ttSelectSubQuestion">Sélectionnez une sous-question</text>
  <text id="ttSkin">Peau</text>
  <text id="ttStart">Début</text>
  <text id="ttStarted">Commencé</text>
  <text id="ttStop">Arrêtez</text>
  <text id="ttStopped">Arrêté</text>
  <text id="ttStartTest">Lancer le test</text>
  <text id="ttStatus">Statut</text>
  <text id="ttStats">Statistiques</text>
  <text id="ttStudent">Étudiant</text>
  <text id="ttStudents">Étudiants</text>
  <text id="ttST10">Dixièmes</text>
  <text id="ttST30">Trentième</text>
  <text id="ttST100">Centième</text>
  <text id="ttSubject">Assujettir</text>
  <text id="ttSubjects">Sujets</text>
  <text id="ttSubmit">Soumettre</text>
  <text id="ttSurname">Nom de famille</text>
  <text id="ttSystem">Système</text>
  <text id="ttSystemConfiguration">Configuration du système</text>
  <text id="ttSbjVers">Version</text>
  <!-- ======================== T ======================== -->
  <text id="ttTeacher">Prof</text>
  <text id="ttTeachers">Enseignants</text>
  <text id="ttTest">Tester</text>
  <text id="ttTests">Des tests</text>
  <text id="ttTestToCorrect">Tests pour corriger</text>
  <text id="ttText">Texte</text>
  <text id="ttTime">Temps</text>
  <text id="ttTimeEnd">Fin du temps</text>
  <text id="ttTimeStart">Heure de début</text>
  <text id="ttTimeUsed">Temps utilisé</text>
  <text id="ttTimeZone">Fuseau horaire</text>
  <text id="ttTitle">Titre</text>
  <text id="ttTopic">Sujet</text>
  <text id="ttTopics">Les sujets</text>
  <text id="ttTopicsAndQuestions">Sujets et questions</text>
  <text id="ttTopicsQuestions">Questions par sujets</text>
  <text id="ttTranslations">Traductions</text>
  <text id="ttTrue">Vrai</text>
  <text id="ttType">Type</text>
  <!-- ======================== U ======================== -->
  <text id="ttUser">Utilisateur</text>
  <text id="ttUsers">Utilisateurs</text>
  <!-- ======================== V ======================== -->
  <text id="ttView">Vue</text>
  <!-- ======================== W ======================== -->
  <text id="ttWelcome">Bienvenue</text>
  <text id="ttWaiting">Attendre</text>
  <text id="ttWarning">Attention</text>
  <!-- ======================== X ======================== -->
  <!-- ======================== Y ======================== -->
  <text id="ttYes">Oui</text>
  <!-- ======================== Z ======================== -->
  <text id="ttAssesmentOverview">Rapport de synthèse d'évaluation</text>
  <text id="ttDeselectAll">Tout déselectionner</text>
  <text id="ttErrorUserParameter">Sélectionnez un détail de participant pour continuer!</text>
  <text id="ttQuestionerror">ID de la question</text>
  <text id="ttRemove">Retirer</text>
  <text id="ttReportCoachingError">Sélectionnez une évaluation et un participant pour continuer</text>
  <text id="ttReportCoachingError2">Sélectionnez une évaluation pour continuer</text>
  <text id="ttReportErrorStudent">L'élève sélectionné n'a pas participé aux tests choisis</text>
  <text id="ttReportMainAO">Principale</text>
  <text id="ttReportTemplateDeleteFailed">La suppression a échoué</text>
  <text id="ttReportTemplateDelet">Modèle supprimé</text>
  <text id="ttReportTemplateLoaded">Modèle caricato correttamente</text>
  <text id="ttReportTemplateSaveError">Insérer un nom de modèle sans espace!</text>
  <text id="ttReportTemplateSaved">Modèle enregistré correctement</text>
  <text id="ttReportTemplateDuplicateError">Le nom du modèle existe déjà!</text>
  <text id="ttReportScoreFilter">Si vous avez déjà sélectionné un participant, veuillez sélectionner à nouveau un nouveau participant.</text>
  <text id="ttSelectAll">Tout sélectionner</text>
  <text id="ttQTFB">Remplir les espaces vides</text>
  <text id="ttQTFB_TEXT">Complétez le texte suivant avec les mots appropriés</text>
  <text id="ttQTFBDescription">Dans une question remplie de blancs, le participant doit compléter le texte avec la bonne réponse dans le champ de texte</text>
  <text id="ttPosterImageVideo">Chargement du logo</text>
  <text id="ttWidthVideo">Largeur</text>
  <text id="ttHeightVideo">la taille</text>
  <text id="ttIdVideo">Code d'identification</text>
  <text id="ttVideoTypeVideo">Format vidéo</text>
  <text id="ttNumberOfPlaysVideo">Nombre maximum de lectures</text>
  <text id="ttToolbarVideo">Vidéo</text>
  <text id="ttDialogTitleVideo">Propriété vidéo</text>
  <text id="ttFakeObjectVideo">Vidéo</text>
  <text id="ttPropertiesVideo">Éditer vidéo</text>
  <text id="ttWidthRequiredVideo">La largeur doit être définie</text>
  <text id="ttHeightRequiredVideo">La hauteur doit être définie</text>
  <text id="ttNumberOfPlayRequiredVideo">Le nombre maximum de lectures doit être défini</text>
  <text id="ttFallbackTemplateVideo">Votre navigateur ne supporte pas la vidéo HTML5</text>
  <text id="ttBrowseVideo">Parcourir le serveur</text>
  <text id="ttsourceVideo">Vidéo source</text>
  <text id="ttNumberOfPlayAlertVideo">Vous avez atteint le nombre maximum de lectures de votre vidéo</text>
  <text id="ttHelpDefault">Panneau d'information</text>
  <text id="ttHelpDefaultDescription">Appuyez sur ce bouton pour obtenir une description de ce que vous pouvez faire.</text>
  <text id="ttHelpQuestion">Sélectionnez une question pour lire son contenu ou double-cliquez pour la modifier.</text>
  <text id="ttHelpADMINNewTeacherDescription">Définir le compte d'un nouvel administrateur, enseignant ou examinateur</text>
  <text id="ttHelpADMINNewStudentDescription">Définir le compte d'un nouvel étudiant</text>
  <text id="ttHelpADMINSelLanguageDescription">Sélectionnez une langue à gérer</text>
  <text id="ttHelpADMINLanguageDescription">Ici vous pouvez changer les localisations des mots utilisés par le système</text>
  <text id="ttHelpADMINSystemConf">Ici, vous pouvez modifier les paramètres EOL, soyez prudent</text>
  <text id="ttHelpADMINRoom">Définir les salles où les tests seront effectués</text>
  <text id="ttHelpADMINImport">This screen allows you to import new questions to Question Mark</text>
  <text id="ttHelpADMINProfile">This screen allows you to edit your profile</text>
  <text id="ttHelpReportAreport">Cet écran vous permet de créer un Areport, il est obligatoire de sélectionner au moins un sujet.</text>
  <text id="ttHelpReportAreportTemplate">Sélectionnez les informations que vous pouvez obtenir dans le rapport.</text>
  <text id="ttHelpReportCreport">Cet écran vous permet de créer un Creport, il est obligatoire de sélectionner un participant.</text>
  <text id="ttHelpReportCreportlist">Sélectionnez l'examen pour créer le rapport</text>
  <text id="ttHelpStudent">To the left are the available tests, to the right the selected examination details</text>
  <text id="ttHelpStudentTest">You are in the exam screen, answer the questions and submit the test</text>
  <text id="ttHelpAdminErrorQuestion">If you find problems you can report from this page.</text>