<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language [
<!ELEMENT language (info+ , text+)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ATTLIST info id ID #IMPLIED>
<!ATTLIST text id ID #IMPLIED>
]>
<language>
  <info id="name">Greek</info>
  <info id="alias">gr</info>
  <!-- ======================== A ======================== -->
  <text id="ttAccountActivation">Ενεργοποίηση Λογαριασμού</text>
  <text id="ttActive">Ενεργός</text>
  <text id="ttActivate">Θέτω εις ενέργειαν</text>
  <text id="ttAdd">Προσθέτω</text>
  <text id="ttAddSelectedStudents">Προσθέστε επιλεγμένους μαθητές</text>
  <text id="ttAdministration">Διαχείριση</text>
  <text id="ttAdministrator">Διαχειριστής</text>
  <text id="ttAdminWelcome">Καλώς ήλθατε στον πίνακα διαχείρισης.</text>
  <text id="ttAlias">Κωδικός ISO 639-1</text>
  <text id="ttAndExit">και Έξοδος</text>
  <text id="ttAnswer">Απάντηση</text>
  <text id="ttAnswers">Απαντήσεις</text>
  <text id="ttArchive">Αρχείο</text>
  <text id="ttArchived">Αρχειοθετημένα</text>
  <text id="ttAssignSubject">Αντιστοίχιση θέματος</text>
  <text id="ttAutomatic">Αυτόματο</text>
  <text id="ttAImportComplete">Ερωτήσεις Η εισαγωγή ολοκληρώθηκε με επιτυχία</text>
  <!-- ======================== B ======================== -->
  <text id="ttBasedOn">Βασισμένο στο</text>
  <text id="ttBlocked">Αποκλεισμένος</text>
  <text id="ttBlock">ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ</text>
  <text id="ttUnblock">Ξεβουλώνω</text>
  <text id="ttBonus">Δώρο</text>
  <!-- ======================== C ======================== -->
  <text id="ttCancel">Ματαίωση</text>
  <text id="ttChangeLanguage">Αλλαξε γλώσσα</text>
  <text id="ttChangeVersion">Αλλαγή δοκιμαστικής έκδοσης</text>
  <text id="ttCheck">Ελεγχος...</text>
  <text id="ttClose">Κοντά</text>
  <text id="ttClosed">Κλειστό</text>
  <text id="ttCorrect">Σωστός</text>
  <text id="ttConfiguration">Διαμόρφωση</text>
  <text id="ttConfirm">Επιβεβαιώνω</text>
  <text id="ttConfirmEmail">Επιβεβαίωση διεύθυνσης ηλεκτρονικού ταχυδρομείου</text>
  <text id="ttConfirmPassword">Επιβεβαίωση Κωδικού</text>
  <text id="ttCreate">Δημιουργώ</text>
  <!-- ==================== CONFIRMS ===================== -->
  <text id="ttCArchiveExam">Είστε βέβαιοι να αρχειοθετήσετε την εξέταση;</text>
  <text id="ttCBlockTest">Είστε βέβαιοι ότι θα εμποδίσετε αυτό το τεστ;</text>
  <text id="ttCChangeStatus">Είστε σίγουροι ότι αλλάζετε την κατάσταση της ερώτησης στο _STATUS_;</text>
  <text id="ttCConfirmTest">Θέλετε να επιβεβαιώσετε τη βαθμολογία της δοκιμής;</text>
  <text id="ttCDeleteAnswer">Είστε σίγουροι ότι θα διαγράψετε αυτήν την απάντηση και τις μεταφράσεις της;</text>
  <text id="ttCDeleteExam">Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτήν την εξέταση;</text>
  <text id="ttCDeleteQuestion">Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτή την ερώτηση και τις μεταφράσεις της;</text>
  <text id="ttCDeleteRoom">Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το δωμάτιο;</text>
  <text id="ttCDeleteSubject">Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το θέμα;</text>
  <text id="ttCDeleteSettings">Είστε σίγουροι ότι θέλετε να διαγράψετε αυτές τις ρυθμίσεις ελέγχου;</text>
  <text id="ttCDeleteTopic">Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το θέμα;</text>
  <text id="ttCDiscardEdits">Οι αλλαγές σας θα χαθούν.</text>
  <text id="ttCDiscardNew">Το δημιουργούμενο στοιχείο θα χαθεί.</text>
  <text id="ttCRegister">Είστε σίγουροι ότι θα εγγραφείτε σε αυτή την εξέταση;</text>
  <text id="ttCRegisterStudents">Είστε σίγουροι ότι θα καταχωρήσετε αυτούς τους επιλεγμένους μαθητές στην εξέταση;</text>
  <text id="ttCRenewPassword">Ο κωδικός της εξέτασης θα αλλάξει.</text>
  <text id="ttCStartExam">Θέλετε να ενεργοποιήσετε την επιλεγμένη εξέταση;</text>
  <text id="ttCStartTest">Θέλετε να ξεκινήσετε τώρα τις εξετάσεις;</text>
  <text id="ttCStopExam">Θέλετε να απενεργοποιήσετε την επιλεγμένη εξέταση;</text>
  <text id="ttCSubmitTest">Θέλετε να υποβάλετε τη δοκιμή σας;</text>
  <text id="ttCTest">Ο κωδικός είναι σωστός.</text>
  <text id="ttCumLaudae">cum Laudae</text>
  <text id="ttCUnblockTest">Είστε σίγουροι ότι θα ξεκλειδώσετε αυτή τη δοκιμή;</text>
  <text id="ttCUpdateConfigurations">Είστε σίγουροι ότι θα αποθηκεύσετε τις νέες διαμορφώσεις του συστήματος;</text>
  <text id="ttCUpdateLanguage">Είστε σίγουροι ότι θα ενημερώσετε τα αρχεία γλώσσας;</text>
  <!-- ======================== D ======================== -->
  <text id="ttD1">Εύκολος</text>
  <text id="ttD2">Μεσαίο</text>
  <text id="ttD3">Σκληρά</text>
  <text id="ttDatabaseConfiguration">Διαμόρφωση βάσης δεδομένων</text>
  <text id="ttDay">Ημέρα</text>
  <text id="ttDelete">Διαγράφω</text>
  <text id="ttDescription">Περιγραφή</text>
  <text id="ttDifficulty">Δυσκολία</text>
  <text id="ttDifficultyQuestions">Ερωτήσεις ανά δυσκολία</text>
  <text id="ttDistribution">Κατανομή</text>
  <text id="ttDo">Κάνετε την εξέταση</text>
  <text id="ttDTAnswerInfo">Εμφανίζονται _TOTAL_ απαντήσεις</text>
  <text id="ttDTAnswerFiltered">(φιλτράρεται από τις συνολικές απαντήσεις _MAX_)</text>
  <text id="ttDTAnswerEmpty">Δεν υπάρχουν απαντήσεις για εμφάνιση</text>
  <text id="ttDTExamInfo">Παρουσιάζονται _TOTAL_ εξετάσεις σε εξέλιξη</text>
  <text id="ttDTExamFiltered">(διηθήθηκε από τις συνολικές εξετάσεις _MAX_ που βρίσκονται σε εξέλιξη)</text>
  <text id="ttDTExamEmpty">Δεν υπάρχουν εξετάσεις για εμφάνιση</text>
  <text id="ttDTQuestionInfo">Εμφανίζονται _TOTAL_ ερωτήσεις</text>
  <text id="ttDTQuestionFiltered">(φιλτραρισμένο από _MAX_ συνολικά ερωτήματα)</text>
  <text id="ttDTQuestionEmpty">Δεν υπάρχουν ερωτήσεις για εμφάνιση</text>
  <text id="ttDTRegisteredStudentInfo">Εμφανίζονται _TOTAL_ εγγεγραμμένοι φοιτητές</text>
  <text id="ttDTRegisteredStudentFiltered">(φιλτραρισμένο από _MAX_ σύνολο εγγεγραμμένων φοιτητών)</text>
  <text id="ttDTRegisteredStudentEmpty">Δεν υπάρχουν εγγεγραμμένοι μαθητές να δείξουν</text>
  <text id="ttDTStudentsInfo">Εμφανίζονται _TOTAL_ φοιτητές</text>
  <text id="ttDTStudentsFiltered">(φιλτραρισμένο από _MAX_ σύνολο φοιτητών)</text>
  <text id="ttDTStudentsEmpty">Κανένας σπουδαστής δεν θα δείξει</text>
  <text id="ttDTTestInfo">Εμφάνιση δοκιμής _TOTAL_</text>
  <text id="ttDTTeacherInfo">Εμφανίζονται _TOTAL_ καθηγητές</text>
  <text id="ttDTTeacherFiltered">(φιλτραρισμένο από τους _MAX_ συνολικά εκπαιδευτικούς)</text>
  <text id="ttDTTeacherEmpty">Δεν υπάρχει δάσκαλος για να δείξει</text>
  <text id="ttDTTestFiltered">(φιλτράρεται από τις συνολικές δοκιμές _MAX_)</text>
  <text id="ttDTTestEmpty">Δεν υπάρχουν δοκιμές για εμφάνιση</text>
  <text id="ttDone">Η εξέταση έγινε</text>
  <text id="ttDuration">Διάρκεια</text>
  <text id="ttDTsubquestionInfo">Υπο ερωτήσεις</text>
  <!-- ======================== E ======================== -->
  <text id="ttEdit">Επεξεργασία</text>
  <text id="ttEditableScore">Επεξεργάσιμη βαθμολογία</text>
  <text id="ttError">Λάθος</text>
  <text id="ttEmail">ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ</text>
  <text id="ttEnd">Τέλος</text>
  <text id="ttEverywhere">Παντού</text>
  <text id="ttExam">Εξέταση</text>
  <text id="ttExams">Εξετάσεις</text>
  <text id="ttExit">Εξοδος</text>
  <text id="ttExtra">Επιπλέον</text>
  <text id="ttExamsArchive">Αρχείο</text>
  <text id="ttExamsInProgress">Οι εξετάσεις βρίσκονται σε εξέλιξη</text>
  <text id="ttETeachers">Εξεταστής</text>
  <text id="ttErrorquestion">Αναφορά σφάλματος</text>
  <!-- ===================== ERRORS ====================== -->
  <text id="ttEActivationFails">Η ενεργοποίηση αποτυγχάνει!</text>
  <text id="ttEAlreadyRegistered">Ο φοιτητής είναι ήδη εγγεγραμμένος για αυτή την εξέταση!</text>
  <text id="ttEAnswerInSet">Η λειτουργία δεν μπορεί να ολοκληρωθεί.</text>
  <text id="ttEAnswerNotFound">Η απάντηση δεν βρέθηκε</text>
  <text id="ttEAnswers">Παρουσιάστηκε ένα πρόβλημα με απαντήσεις.</text>
  <text id="ttEDatabase">Σφάλμα βάσης δεδομένων!</text>
  <text id="ttEDates">Οι ημερομηνίες δεν είναι σωστές!</text>
  <text id="ttEEditRoomAll">Δεν είναι δυνατή η επεξεργασία του "ολόκληρου" του δωματίου!</text>
  <text id="ttEEmailAlreadyRegistered">E-mail έχει ήδη εγγραφεί!</text>
  <text id="ttEEmailNotRegistered">Το ηλεκτρονικό ταχυδρομείο δεν έχει εγγραφεί!</text>
  <text id="ttEEmailNotValid">Το δακτυλογραφημένο ηλεκτρονικό ταχυδρομείο δεν είναι έγκυρο!</text>
  <text id="ttEEmailsNotMatch">Τα δύο μηνύματα ηλεκτρονικού ταχυδρομείου δεν ταιριάζουν!</text>
  <text id="ttEEmptyFields">Ένα ή περισσότερα πεδία είναι κενά!</text>
  <text id="ttEExamArchived">Η λειτουργία δεν μπορεί να ολοκληρωθεί.</text>
  <text id="ttEExamNotFound">Η εξέταση δεν βρέθηκε!</text>
  <text id="ttEExamNotStarted">Δεν μπορείτε να ξεκινήσετε την εξέταση.</text>
  <text id="ttEExamStarted">Η λειτουργία δεν μπορεί να ολοκληρωθεί επειδή η εξέταση έχει ήδη ξεκινήσει!</text>
  <text id="ttEExamWaiting">Η λειτουργία δεν μπορεί να ολοκληρωθεί επειδή η εξέταση δεν ξεκίνησε ποτέ!</text>
  <text id="ttEExamsNotArchivedDeleteTopic">Η λειτουργία δεν μπορεί να ολοκληρωθεί, επειδή τουλάχιστον μία μη αρχειοθετημένη εξέταση περιέχει ερωτήσεις από αυτό το θέμα!</text>
  <text id="ttEExamsNotArchivedEditTestSettings">Η λειτουργία δεν μπορεί να ολοκληρωθεί, επειδή αυτές οι ρυθμίσεις χρησιμοποιούνται από τουλάχιστον μία μη αρχειοθετημένη εξέταση.</text>
  <text id="ttEExamsNotArchivedDeleteTestSettings">Η λειτουργία δεν μπορεί να ολοκληρωθεί, επειδή αυτές οι ρυθμίσεις χρησιμοποιούνται από τουλάχιστον μία μη αρχειοθετημένη εξέταση!</text>
  <text id="ttEIncorrectField">Ένα ή περισσότερα πεδία δεν είναι σωστά!</text>
  <text id="ttELogin">Το ηλεκτρονικό ταχυδρομείο και / ή ο κωδικός πρόσβασης δεν είναι σωστά!</text>
  <text id="ttEMainLanguageEmpty">Η κύρια γλώσσα του αντικειμένου δεν μπορεί να είναι κενή!</text>
  <text id="ttEMandatoryQuestion">Αυτή είναι μια υποχρεωτική ερώτηση σχετικά με τη ρύθμιση δοκιμής '_TESTSETTING_': δεν μπορείτε να την διαγράψετε ή να επεξεργαστείτε τη δυσκολία ή το θέμα της.</text>
  <text id="ttENotAuthorized">Ο πελάτης σας δεν είναι εξουσιοδοτημένος.</text>
  <text id="ttENoStudentsToRegister">Κανένας φοιτητής να εγγραφεί</text>
  <text id="ttENoTopicsForSubject">Δεν υπάρχει θέμα για αυτό το θέμα!</text>
  <text id="ttEOldPasswordWrong">Ο παλιός κωδικός πρόσβασης δεν είναι σωστός!</text>
  <text id="ttEPassword">Λάθος κωδικός!</text>
  <text id="ttEPasswordShort">Ο κωδικός πρόσβασης είναι πολύ μικρός.</text>
  <text id="ttEPasswordsNotMatch">Οι δύο κωδικοί πρόσβασης δεν ταιριάζουν!</text>
  <text id="ttEQuestAnswPicker">Σφάλμα κατά την επιλογή των ερωτήσεων και των απαντήσεων.</text>
  <text id="ttEQuestionInSet">Η λειτουργία δεν μπορεί να ολοκληρωθεί.</text>
  <text id="ttEQuestionNotFound">Η ερώτηση δεν βρέθηκε!</text>
  <text id="ttEQuestionType">Ο τύπος ερωτήματος δεν είναι σωστός!</text>
  <text id="ttERegFailedQuestions">Η καταχώριση απέτυχε: πολύ λίγες ερωτήσεις!</text>
  <text id="ttERoomAllDelete">Το 'Όλα' δεν μπορεί να διαγραφεί!</text>
  <text id="ttERoomUsed">Η λειτουργία δεν μπορεί να ολοκληρωθεί.</text>
  <text id="ttESaveBeforeNew">Πριν δημιουργήσετε ένα νέο στοιχείο, αποθηκεύστε ή ακυρώστε το ήδη δημιουργημένο στοιχείο.</text>
  <text id="ttESelectQuestionType">Πρέπει να επιλέξετε έναν από τους διαθέσιμους τύπους ερωτήσεων!</text>
  <text id="ttESelectSubject">Πρέπει να επιλέξετε ένα από τα θέματα σας!</text>
  <text id="ttESelectTestSettings">Πρέπει να επιλέξετε μία από τις ρυθμίσεις ελέγχου!</text>
  <text id="ttESetNotFound">Οι ερωτήσεις δεν βρέθηκαν!</text>
  <text id="ttETestAlreadyArchived">Η λειτουργία δεν μπορεί να ολοκληρωθεί.</text>
  <text id="ttETestAlreadySubmitted">Η λειτουργία δεν μπορεί να ολοκληρωθεί.</text>
  <text id="ttETestBlockedSubmitted">Η λειτουργία δεν μπορεί να ολοκληρωθεί.</text>
  <text id="ttETestNotArchived">Η λειτουργία δεν μπορεί να ολοκληρωθεί.</text>
  <text id="ttETestNotFound">Η δοκιμή δεν βρέθηκε!</text>
  <text id="ttETestsNotArchived">Ορισμένες δοκιμές δεν έχουν αρχειοθετηθεί!</text>
  <text id="ttETestSettingDeleteQuestion">Η λειτουργία δεν μπορεί να ολοκληρωθεί.</text>
  <text id="ttETestSettingDeleteTopic">Η λειτουργία δεν μπορεί να ολοκληρωθεί.</text>
  <text id="ttETimeExpired">Ο διαθέσιμος χρόνος έχει λήξει!</text>
  <text id="ttETranslationExists">Η μετάφραση της επιλεγμένης γλώσσας υπάρχει ήδη!</text>
  <text id="ttEUserNotFound">Ο χρήστης δεν βρέθηκε!</text>
  <text id="ttEValues">Ορισμένες τιμές δεν είναι σωστές!</text>
  <!-- ======================== F ======================== -->
  <text id="ttFalse">Ψευδής</text>
  <text id="ttFinalScore">Τελικό σκορ</text>
  <!-- ======================== G ======================== -->
  <text id="ttGeneralInformations">Γενικές πληροφορίες</text>
  <!-- ======================== H ======================== -->
  <text id="ttHours">ώρες</text>
  <text id="ttHome">Σπίτι</text>
  <text id="ttHomepage">Αρχική σελίδα</text>
  <text id="ttHost">Πλήθος</text>
  <!-- ======================= HELP ====================== -->
  <text id="ttHAnswPanel">Κάντε διπλό κλικ για να επεξεργαστείτε την επιλεγμένη απάντηση</text>
  <text id="ttHQuestLanguagesPanel">Κάντε κλικ για να εμφανιστεί η μετάφραση της επιλεγμένης ερώτησης</text>
  <text id="ttHQuestPanel">Κάντε ένα κλικ για να επιλέξετε και να προβάλετε την προεπισκόπηση ερωτήσεων και κάντε διπλό κλικ για να επεξεργαστείτε τις ερωτήσεις και τις απαντήσεις.</text>
  <text id="ttHQuestPreviewPanel">Οι απαντήσεις με πορτοκαλί φόντο δεν μεταφράζονται σε γλώσσα που ζητήσατε</text>
  <text id="ttHQuestTopicPanel">Κάντε ένα κλικ για να φιλτράρετε ερωτήσεις και κάντε διπλό κλικ για να επεξεργαστείτε τις πληροφορίες σχετικά με το θέμα</text>
  <!-- ======================== I ======================== -->
  <text id="ttInfo">Πληροφορίες</text>
  <text id="ttIPEnd">IPv4 Τέλος</text>
  <text id="ttIPStart">IPv4 Έναρξη</text>
  <text id="ttInactive">Αδρανής</text>
  <text id="ttImportQM">Εισαγωγή</text>
  <text id="ttImport">Εισαγωγή QM</text>
  <text id="ttImportComplete">Ερωτήσεις Η εισαγωγή ολοκληρώθηκε με επιτυχία</text>
  <!-- ======================== J ======================== -->
  <text id="ttJoin">Συμμετοχή</text>
  <!-- ======================== K ======================== -->
  <!-- ======================== L ======================== -->
  <text id="ttLanguage">Γλώσσα</text>
  <text id="ttLanguages">Γλώσσες</text>
  <text id="ttLogin">Σύνδεση</text>
  <text id="ttLogo">Λογότυπο</text>
  <text id="ttLoginOk">Η σύνδεση ολοκληρώθηκε!</text>
  <text id="ttLogout">ΑΠΟΣΥΝΔΕΣΗ</text>
  <!-- ======================== M ======================== -->
  <text id="ttMailLostPassword">Για να επαναφέρετε τον κωδικό πρόσβασης του λογαριασμού σας, κάντε κλικ στον παρακάτω σύνδεσμο: _LINK_ Εάν δεν έχετε ζητήσει επαναφορά κωδικού πρόσβασης, αγνοήστε αυτό το μήνυμα ηλεκτρονικού ταχυδρομείου.</text>
  <text id="ttMailCredentials">Αγαπητέ _USERNAME_, Ο κωδικός πρόσβασής σας που έχει συσχετιστεί με τον λογαριασμό _USEREMAIL_ έχει τροποποιηθεί σύμφωνα με το αίτημά σας.</text>
  <text id="ttMailNewTeacher">Καλώς ήρθατε στο _SYSTEMNAME_.</text>
  <text id="ttMainLanguage">Κύρια γλώσσα</text>
  <text id="ttManage">Διαχειρίζονται</text>
  <text id="ttMandatory">Επιτακτικός</text>
  <text id="ttManual">Εγχειρίδιο</text>
  <text id="ttMinutes">λεπτά</text>
  <text id="ttMyExams">Οι εξετάσεις μου</text>
  <text id="ttMySettings">Οι ρυθμίσεις μου</text>
  <text id="ttMySubjects">Επιλέξτε θέμα</text>
  <!-- ==================== MESSAGES ===================== -->
  <text id="ttMActivation">Ο κωδικός πρόσβασης έχει ρυθμιστεί με επιτυχία.</text>
  <text id="ttMAnswerDeleted">Η απάντηση διαγράφηκε με επιτυχία</text>
  <text id="ttMConfigurationsUpdated">Οι διαμορφώσεις συστημάτων ενημερώθηκαν με επιτυχία</text>
  <text id="ttMConfirm">Η δοκιμή επιβεβαιώθηκε με επιτυχία και αρχειοθετείται</text>
  <text id="ttMUserCreated">Η δημιουργία ολοκληρώθηκε: ένα μήνυμα ηλεκτρονικού ταχυδρομείου σας έχει σταλεί για να ολοκληρώσετε την εγγραφή.</text>
  <text id="ttMEdit">Οι επεξεργασίες αποθηκεύτηκαν με επιτυχία</text>
  <text id="ttMExamArchived">Η εξέταση ολοκληρώθηκε με επιτυχία</text>
  <text id="ttMExamDeleted">Η εξέταση διαγράφηκε με επιτυχία</text>
  <text id="ttMExamStarted">Η εξέταση ξεκίνησε με επιτυχία</text>
  <text id="ttMExamStopped">Η εξέταση έπαψε επιτυχώς</text>
  <text id="ttMLanguageCreated">Η μετάφραση δημιουργήθηκε με επιτυχία</text>
  <text id="ttMLanguageSaved">Η μετάφραση αποθηκεύτηκε με επιτυχία</text>
  <text id="ttMLanguageUpdated">Η μετάφραση ενημερώθηκε με επιτυχία</text>
  <text id="ttMNewAnswer">Η απάντηση δημιουργήθηκε με επιτυχία</text>
  <text id="ttMNewQuestion">Η ερώτηση δημιουργήθηκε με επιτυχία</text>
  <text id="ttMNewRoom">Η αίθουσα δημιουργήθηκε με επιτυχία</text>
  <text id="ttMNewSettings">Οι ρυθμίσεις δοκιμής δημιουργήθηκαν με επιτυχία</text>
  <text id="ttMNewSubject">Το θέμα δημιουργήθηκε με επιτυχία</text>
  <text id="ttMNewTopic">Το θέμα δημιουργήθηκε με επιτυχία</text>
  <text id="ttMPasswordRenewed">Ο κωδικός της εξέτασης ολοκληρώθηκε με επιτυχία</text>
  <text id="ttMQuestionDeleted">Η ερώτηση διαγράφεται με επιτυχία</text>
  <text id="ttMRegistration">Έχετε εγγραφεί επιτυχώς σε αυτήν την εξέταση</text>
  <text id="ttMResetConfirmed">Η αίτηση ολοκληρώθηκε: έχει σταλεί ένα μήνυμα ηλεκτρονικού ταχυδρομείου σε εσάς για να επαναφέρετε τον κωδικό πρόσβασης.</text>
  <text id="ttMRoomDeleted">Το δωμάτιο διαγράφηκε με επιτυχία</text>
  <text id="ttMSelectLanguage">Επιλέξτε τη γλώσσα που θέλετε να διαχειριστείτε</text>
  <text id="ttMSettingsDeleted">Οι ρυθμίσεις δοκιμής διαγράφηκαν με επιτυχία</text>
  <text id="ttMStudentsRegistered">Οι φοιτητές έχουν εγγραφεί επιτυχώς στην εξέταση</text>
  <text id="ttMSubjectDeleted">Το θέμα διαγράφηκε με επιτυχία</text>
  <text id="ttMSubjectQuestions">Για να διαχειριστείτε θέματα και ερωτήσεις, επιλέξτε το θέμα</text>
  <text id="ttMSubjectSettings">Για να διαχειριστείτε τις ρυθμίσεις των εξετάσεων, επιλέξτε το θέμα</text>
  <text id="ttMTestBlocked">Η δοκιμή ολοκληρώθηκε με επιτυχία</text>
  <text id="ttMTestSubmitted">Η δοκιμή υποβλήθηκε με επιτυχία</text>
  <text id="ttMTestUnblocked">Η δοκιμή ξεκλειδώθηκε με επιτυχία</text>
  <text id="ttMTopicDeleted">Το θέμα διαγράφηκε με επιτυχία</text>
  <!-- ======================== N ======================== -->
  <text id="ttName">Ονομα</text>
  <text id="ttNumberError">Η τιμή πρέπει να είναι ακέραιος ή δεκαδικός (ES: 12,5)</text>
  <text id="ttNegativeScores">Αρνητικές βαθμολογίες</text>
  <text id="ttNew">Νέος</text>
  <text id="ttNext">Επόμενο</text>
  <text id="ttNewAnswer">Νέα απάντηση</text>
  <text id="ttNewCredentials">Νέα διαπιστευτήρια</text>
  <text id="ttNewLanguage">Νέα Γλώσσα</text>
  <text id="ttNewPassword">νέος κωδικός πρόσβασης</text>
  <text id="ttNewQuestion">Νέα ερώτηση</text>
  <text id="ttNewRegistration">Νέα καταχώρηση</text>
  <text id="ttNewRoom">Νέο Δωμάτιο</text>
  <text id="ttNewTeacher">Νέος δάσκαλος</text>
  <text id="ttNewTestSettings">Νέες ρυθμίσεις</text>
  <text id="ttNewSubject">Νέο θέμα</text>
  <text id="ttNewStudent">Νέος μαθητής</text>
  <text id="ttNewTopic">Νέο θέμα</text>
  <text id="ttNewUser">Νέος χρήστης</text>
  <text id="ttNo">Οχι</text>
  <text id="ttNoAnswers">Δεν υπάρχουν διαθέσιμες απαντήσεις για αυτήν την ερώτηση</text>
  <text id="ttNoExams">Δεν υπάρχουν διαθέσιμες εξετάσεις για αυτό το θέμα</text>
  <text id="ttNoExamInProgress">Δεν υπάρχουν εξετάσεις σε εξέλιξη</text>
  <text id="ttNoInfo">Δεν υπάρχουν πληροφορίες σχετικά με αυτήν την εξέταση</text>
  <text id="ttNoQuestions">Δεν υπάρχουν διαθέσιμες ερωτήσεις για αυτό το θέμα</text>
  <text id="ttNoRooms">Δεν δημιουργήθηκαν δωμάτια: "Όλα" μόνο διαθέσιμα</text>
  <text id="ttNoSettings">Δεν υπάρχουν διαθέσιμες ρυθμίσεις για αυτό το θέμα</text>
  <text id="ttNoSubjects">Δεν υπάρχουν διαθέσιμα θέματα</text>
  <text id="ttNoTestToCorrect">Δεν υπάρχουν δοκιμές για να διορθωθούν</text>
  <text id="ttNoUserRegistered">Δεν υπάρχουν εγγεγραμμένοι χρήστες για αυτήν την εξέταση</text>
  <!-- ======================== O ======================== -->
  <text id="ttOldPassword">ΠΑΛΙΟΣ ΚΩΔΙΚΟΣ</text>
  <text id="ttEssayQuestion">Ερώτηση για το δοκίμιο</text>
  <!-- ======================== P ======================== -->
  <text id="ttPassword">Κωδικός πρόσβασης</text>
  <text id="ttPasswordLost">Ο κωδικός πρόσβασης χάθηκε;</text>
  <text id="ttPort">Λιμάνι</text>
  <text id="ttProfile">Προφίλ</text>
  <text id="ttPrepareImportQM">Προεπισκόπηση</text>
  <!-- ======================== Q ======================== -->
  <text id="ttQuestion">Ερώτηση</text>
  <text id="ttQuestionPreview">Προεπισκόπηση ερωτήματος</text>
  <text id="ttQuestions">Ερωτήσεις</text>
  <text id="ttQEc">Αριθμομηχανή</text>
  <text id="ttQEp">Περιοδικός Πίνακας</text>
  <text id="ttQTMC">Πολλαπλή επιλογή</text>
  <text id="ttQTMCDescription">Σε μια ερώτηση πολλαπλής επιλογής ο συμμετέχων επιλέγει μία μόνο επιλογή από μια σειρά επιλογών για να απαντήσει στην ερώτηση.</text>
  <text id="ttQTMR">Πολλαπλή απάντηση</text>
  <text id="ttQTMRDescription">Μια ερώτηση πολλαπλής απάντησης είναι σαν μια πολλαπλή επιλογή, εκτός από το ότι αντί να απαιτείται να κάνετε το πολύ μία επιλογή, ο χρήστης μπορεί να κάνει μία ή περισσότερες από μία επιλογές.</text>
  <text id="ttQTES">Ερώτηση για το δοκίμιο</text>
  <text id="ttQTESDescription">Μια ερώτηση για το δοκίμιο επιτρέπει στον συμμετέχοντα να εισαγάγει μια μακρά απάντηση κειμένου ελεύθερου εύρους σε μια ερώτηση.</text>
  <text id="ttQTYN">Ναι όχι</text>
  <text id="ttQTYNDescription">Η ερώτηση Ναι / Όχι είναι μια ερώτηση πολλαπλής επιλογής που ζητά από τον συμμετέχοντα να δώσει μια απάντηση "Ναι" ή "Όχι" σε μια ερώτηση.</text>
  <text id="ttQTTF">Σωστό Λάθος</text>
  <text id="ttQTTFDescription">Μια αληθινή / ψεύτικη ερώτηση είναι μια ερώτηση πολλαπλής επιλογής που ζητά από τον συμμετέχοντα να δώσει μια "αληθινή" ή "ψευδή" απάντηση σε μια ερώτηση.</text>
  <text id="ttQTNM">Αριθμητικός</text>
  <text id="ttQTNMDescription">Σε μια Αριθμητική Ερώτηση, ο συμμετέχων απαντά πληκτρολογώντας είτε έναν ολόκληρο αριθμό είτε έναν πραγματικό αριθμό.</text>
  <text id="ttQTTM">Ταίριασμα κειμένου</text>
  <text id="ttQTTMDescription">Σε μια ερώτηση για την αντιστοίχιση κειμένου, ο συμμετέχων πληκτρολογεί με μία λέξη ή μερικές λέξεις για να δείξει την απάντησή του.</text>
  <text id="ttQTHS">Hotspot</text>
  <text id="ttQTHSDescription">Μια ερώτηση Hotspot είναι μια ερώτηση drag-and-drop μόνο με μία σωστή περιοχή.</text>
  <text id="ttQTPL">Τραβήξτε τον κατάλογο</text>
  <text id="ttQuesionid">Αναγνωριστικό ερωτήματος</text>
  <text id="ttQuestionNotes">Περιγραφή</text>
  <text id="ttQuestionsend">Αποστολή αναφοράς</text>
  <text id="ttQuestionreporting">Για να αναφέρετε περισσότερες ερωτήσεις, πρέπει να αφήσετε το πεδίο id κενό</text>
  <!-- ======================== R ======================== -->
  <text id="ttRandom">Τυχαίος</text>
  <text id="ttRefresh">Φρεσκάρω</text>
  <text id="ttRegister">Κανω ΕΓΓΡΑΦΗ</text>
  <text id="ttRegistrations">Εγγραφές</text>
  <text id="ttRegEnd">Κατάργηση καταχώρισης</text>
  <text id="ttRenewPassword">Ανανέωση κωδικού πρόσβασης</text>
  <text id="ttReset">Επαναφορά</text>
  <text id="ttResetPassword">Επαναφέρετε τον κωδικό πρόσβασης</text>
  <text id="ttRole">Ρόλος</text>
  <text id="ttRooms">Δωμάτια</text>
  <!-- ======================== S ======================== -->
  <text id="ttSave">Αποθηκεύσετε</text>
  <text id="ttSaveAnswerInfo">Αποθήκευση πληροφοριών απάντησης</text>
  <text id="ttSaveLanguageFiles">Αποθήκευση αρχείων γλώσσας</text>
  <text id="ttSaveLanguageXML">Αποθήκευση αρχείων γλώσσας XML</text>
  <text id="ttSaveQuestionInfo">Αποθήκευση πληροφοριών ερωτήσεων</text>
  <text id="ttScore">Σκορ</text>
  <text id="ttScoreFinal">Τελικό σκορ</text>
  <text id="ttScoreTest">Αποτέλεσμα δοκιμής</text>
  <text id="ttScoreType">Τύπος βαθμολογίας</text>
  <text id="ttScoreMin">Ελάχιστη βαθμολογία</text>
  <text id="ttSelectSubject">Επιλέξτε Θέμα</text>
  <text id="ttSelectSubjectBefore">Επιλέξτε ένα θέμα πριν</text>
  <text id="ttSet">Σειρά</text>
  <text id="ttSetPassword">Ορίστε τον κωδικό πρόσβασής σας</text>
  <text id="ttSettings">Ρυθμίσεις</text>
  <text id="ttShowHide">Εμφάνιση απόκρυψη</text>
  <text id="ttSelectSubQuestion">Επιλέξτε μια υποQuestion</text>
  <text id="ttSkin">Δέρμα</text>
  <text id="ttStart">Αρχή</text>
  <text id="ttStarted">Ξεκίνησε</text>
  <text id="ttStop">Να σταματήσει</text>
  <text id="ttStopped">Σταμάτησε</text>
  <text id="ttStartTest">Ξεκινήστε τη δοκιμή</text>
  <text id="ttStatus">Κατάσταση</text>
  <text id="ttStats">Στατιστικά στοιχεία</text>
  <text id="ttStudent">Μαθητης σχολειου</text>
  <text id="ttStudents">Φοιτητές</text>
  <text id="ttST10">Δέκατα</text>
  <text id="ttST30">Τριάντα</text>
  <text id="ttST100">Εκατοστός</text>
  <text id="ttSubject">Θέμα</text>
  <text id="ttSubjects">μαθήματα</text>
  <text id="ttSubmit">υποβάλλουν</text>
  <text id="ttSurname">Επώνυμο</text>
  <text id="ttSystem">Σύστημα</text>
  <text id="ttSystemConfiguration">Διαμόρφωση συστήματος</text>
  <text id="ttSbjVers">Εκδοχή</text>
  <!-- ======================== T ======================== -->
  <text id="ttTeacher">Δάσκαλος</text>
  <text id="ttTeachers">Δάσκαλοι</text>
  <text id="ttTest">Δοκιμή</text>
  <text id="ttTests">Δοκιμές</text>
  <text id="ttTestToCorrect">Δοκιμές για διόρθωση</text>
  <text id="ttText">Κείμενο</text>
  <text id="ttTime">χρόνος</text>
  <text id="ttTimeEnd">Τέλος χρόνου</text>
  <text id="ttTimeStart">Ώρα έναρξης</text>
  <text id="ttTimeUsed">Χρόνος που χρησιμοποιήθηκε</text>
  <text id="ttTimeZone">Ζώνη ώρας</text>
  <text id="ttTitle">Τίτλος</text>
  <text id="ttTopic">Θέμα</text>
  <text id="ttTopics">Θέματα</text>
  <text id="ttTopicsAndQuestions">Θέματα και Ερωτήσεις</text>
  <text id="ttTopicsQuestions">Ερωτήσεις ανά Θέματα</text>
  <text id="ttTranslations">Μεταφράσεις</text>
  <text id="ttTrue">Αληθής</text>
  <text id="ttType">Τύπος</text>
  <!-- ======================== U ======================== -->
  <text id="ttUser">Χρήστης</text>
  <text id="ttUsers">Χρήστες</text>
  <!-- ======================== V ======================== -->
  <text id="ttView">Θέα</text>
  <!-- ======================== W ======================== -->
  <text id="ttWelcome">καλως ΗΡΘΑΤΕ</text>
  <text id="ttWaiting">Αναμονή</text>
  <text id="ttWarning">Προειδοποίηση</text>
  <!-- ======================== X ======================== -->
  <!-- ======================== Y ======================== -->
  <text id="ttYes">Ναί</text>
  <!-- ======================== Z ======================== -->
  <text id="ttAssesmentOverview">Αναφορά επισκόπησης αξιολόγησης</text>
  <text id="ttDeselectAll">Αποεπιλογή όλων</text>
  <text id="ttErrorUserParameter">Επιλέξτε μια λεπτομέρεια συμμετέχοντα για να συνεχίσετε!</text>
  <text id="ttQuestionerror">Αναγνωριστικό ερωτήματος</text>
  <text id="ttRemove">Αφαιρώ</text>
  <text id="ttReportCoachingError">Επιλέξτε μια αξιολόγηση και έναν συμμετέχοντα για να συνεχίσετε</text>
  <text id="ttReportCoachingError2">Επιλέξτε αξιολόγηση για να συνεχίσετε</text>
  <text id="ttReportErrorStudent">Ο επιλεγμένος φοιτητής δεν συμμετείχε σε επιλεγμένες εξετάσεις</text>
  <text id="ttReportMainAO">Κύριος</text>
  <text id="ttReportTemplateDeleteFailed">Η διαγραφή απέτυχε</text>
  <text id="ttReportTemplateDelet">Το πρότυπο διαγράφηκε</text>
  <text id="ttReportTemplateLoaded">Πρότυπο caricato correttamente</text>
  <text id="ttReportTemplateSaveError">Εισαγάγετε ένα όνομα προτύπου χωρίς χώρο!</text>
  <text id="ttReportTemplateSaved">Το πρότυπο αποθηκεύτηκε σωστά</text>
  <text id="ttReportTemplateDuplicateError">Το όνομα προτύπου υπάρχει ήδη!</text>
  <text id="ttReportScoreFilter">Αν έχετε ήδη επιλέξει έναν συμμετέχοντα, τώρα επιλέξτε ξανά ένα νέο</text>
  <text id="ttSelectAll">Επιλογή όλων</text>
  <text id="ttQTFB">Συμπλήρωσε τα κενά</text>
  <text id="ttQTFB_TEXT">Συμπληρώστε το ακόλουθο κείμενο με τις κατάλληλες λέξεις</text>
  <text id="ttQTFBDescription">Σε μια συμπλήρωση κενών ερωτήσεων ο συμμετέχων πρέπει να συμπληρώσει το κείμενο με τη σωστή απάντηση στο πεδίο κειμένου</text>
  <text id="ttPosterImageVideo">Φόρτωση λογοτύπου</text>
  <text id="ttWidthVideo">Πλάτος</text>
  <text id="ttHeightVideo">Υψος</text>
  <text id="ttIdVideo">Κωδικός αναγνώρισης</text>
  <text id="ttVideoTypeVideo">Βίντεο μορφή</text>
  <text id="ttNumberOfPlaysVideo">Μέγιστος αριθμός αναπαραστάσεων</text>
  <text id="ttToolbarVideo">βίντεο</text>
  <text id="ttDialogTitleVideo">Ιδιότητα βίντεο</text>
  <text id="ttFakeObjectVideo">βίντεο</text>
  <text id="ttPropertiesVideo">Επεξεργασία βίντεο</text>
  <text id="ttWidthRequiredVideo">Το πλάτος πρέπει να ρυθμιστεί</text>
  <text id="ttHeightRequiredVideo">Το ύψος πρέπει να ρυθμιστεί</text>
  <text id="ttNumberOfPlayRequiredVideo">Πρέπει να οριστεί ο μέγιστος αριθμός αναπαραγωγών</text>
  <text id="ttFallbackTemplateVideo">Το πρόγραμμα περιήγησής σας δεν υποστηρίζει βίντεο HTML5</text>
  <text id="ttBrowseVideo">Αναζήτηση διακομιστή</text>
  <text id="ttsourceVideo">Πηγή βίντεο</text>
  <text id="ttNumberOfPlayAlertVideo">Έχετε φτάσει στον μέγιστο αριθμό αναπαραγωγών του βίντεό σας</text>
  <text id="ttHelpDefault">Πίνακας πληροφοριών</text>
  <text id="ttHelpDefaultDescription">Πατήστε αυτό το κουμπί για να δείτε μια περιγραφή του τι μπορείτε να κάνετε</text>
  <text id="ttHelpQuestion">Επιλέξτε μια ερώτηση για να διαβάσετε τα περιεχόμενά της ή κάντε διπλό κλικ για επεξεργασία</text>
  <text id="ttHelpADMINNewTeacherDescription">Καθορίστε το λογαριασμό ενός νέου διαχειριστή, εκπαιδευτή ή εξεταστή</text>
  <text id="ttHelpADMINNewStudentDescription">Καθορίστε το λογαριασμό ενός νέου φοιτητή</text>
  <text id="ttHelpADMINSelLanguageDescription">Επιλέξτε μια γλώσσα που θέλετε να διαχειριστείτε</text>
  <text id="ttHelpADMINLanguageDescription">Εδώ μπορείτε να αλλάξετε τις τοποθεσίες των λέξεων που χρησιμοποιούνται από το σύστημα</text>
  <text id="ttHelpADMINSystemConf">Εδώ μπορείτε να αλλάξετε τις ρυθμίσεις EOL, προσέξτε</text>