<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language [
<!ELEMENT language (info+ , text+)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ATTLIST info id ID #IMPLIED>
<!ATTLIST text id ID #IMPLIED>
]>
<language>
  <info id="name">Polskie</info>
  <info id="alias">pl</info>
  <!-- ======================== A ======================== -->
  <text id="ttAccountActivation">Aktywacja konta</text>
  <text id="ttActive">Aktywny</text>
  <text id="ttActivate">Aktywuj</text>
  <text id="ttAdd">Dodaj</text>
  <text id="ttAddSelectedStudents">Dodaj wybranych uczniów</text>
  <text id="ttAdministration">Podawanie</text>
  <text id="ttAdministrator">Administrator</text>
  <text id="ttAdminWelcome">Witamy w panelu administracyjnym.</text>
  <text id="ttAlias">Kod ISO 639-1</text>
  <text id="ttAndExit">i Wyjdź</text>
  <text id="ttAnswer">Odpowiedź</text>
  <text id="ttAnswers">Odpowiedzi</text>
  <text id="ttArchive">Archiwum</text>
  <text id="ttArchived">Zarchiwizowane</text>
  <text id="ttAssignSubject">Przypisz podmiot</text>
  <text id="ttAutomatic">Automatyczny</text>
  <text id="ttAImportComplete">Pytania Import już zakończony</text>
  <!-- ======================== B ======================== -->
  <text id="ttBasedOn">Oparte na</text>
  <text id="ttBlocked">Zablokowany</text>
  <text id="ttBlock">Blok</text>
  <text id="ttUnblock">Odblokować</text>
  <text id="ttBonus">Premia</text>
  <!-- ======================== C ======================== -->
  <text id="ttCancel">Anuluj</text>
  <text id="ttChangeLanguage">Zmień język</text>
  <text id="ttChangeVersion">Zmień wersję testową</text>
  <text id="ttCheck">Czek...</text>
  <text id="ttClose">Blisko</text>
  <text id="ttClosed">Zamknięte</text>
  <text id="ttCorrect">Poprawny</text>
  <text id="ttConfiguration">Konfiguracja</text>
  <text id="ttConfirm">Potwierdzać</text>
  <text id="ttConfirmEmail">Potwierdź email</text>
  <text id="ttConfirmPassword">Potwierdź hasło</text>
  <text id="ttCreate">Stwórz</text>
  <!-- ==================== CONFIRMS ===================== -->
  <text id="ttCArchiveExam">Czy na pewno zarchiwizujesz egzamin?</text>
  <text id="ttCBlockTest">Czy na pewno chcesz zablokować ten test?</text>
  <text id="ttCChangeStatus">Czy na pewno zmienisz status pytania na _STATUS_?</text>
  <text id="ttCConfirmTest">Czy chcesz potwierdzić wynik testu?</text>
  <text id="ttCDeleteAnswer">Czy na pewno chcesz usunąć tę odpowiedź i jej tłumaczenia?</text>
  <text id="ttCDeleteExam">Czy na pewno chcesz usunąć ten egzamin?</text>
  <text id="ttCDeleteQuestion">Czy na pewno chcesz usunąć to pytanie i jego tłumaczenia?</text>
  <text id="ttCDeleteRoom">Czy na pewno chcesz usunąć ten pokój?</text>
  <text id="ttCDeleteSubject">Czy na pewno chcesz usunąć ten temat?</text>
  <text id="ttCDeleteSettings">Czy na pewno chcesz usunąć te ustawienia testowe?</text>
  <text id="ttCDeleteTopic">Czy na pewno chcesz usunąć ten temat?</text>
  <text id="ttCDiscardEdits">Twoje zmiany zostaną utracone.</text>
  <text id="ttCDiscardNew">Utworzony element zostanie utracony.</text>
  <text id="ttCRegister">Czy na pewno chcesz zarejestrować się na tym egzaminie?</text>
  <text id="ttCRegisterStudents">Czy na pewno chcesz zarejestrować tych wybranych uczniów na egzaminie?</text>
  <text id="ttCRenewPassword">Hasło egzaminu zostanie zmienione.</text>
  <text id="ttCStartExam">Czy chcesz aktywować wybrany egzamin?</text>
  <text id="ttCStartTest">Czy chcesz teraz rozpocząć egzamin?</text>
  <text id="ttCStopExam">Czy chcesz dezaktywować wybrany egzamin?</text>
  <text id="ttCSubmitTest">Czy chcesz przesłać test?</text>
  <text id="ttCTest">Hasło jest poprawne.</text>
  <text id="ttCumLaudae">cum Laudae</text>
  <text id="ttCUnblockTest">Czy na pewno chcesz odblokować ten test?</text>
  <text id="ttCUpdateConfigurations">Czy na pewno chcesz zapisać nowe konfiguracje systemu?</text>
  <text id="ttCUpdateLanguage">Czy na pewno chcesz zaktualizować pliki językowe?</text>
  <!-- ======================== D ======================== -->
  <text id="ttD1">Łatwy</text>
  <text id="ttD2">Średni</text>
  <text id="ttD3">Ciężko</text>
  <text id="ttDatabaseConfiguration">Konfiguracja bazy danych</text>
  <text id="ttDay">Dzień</text>
  <text id="ttDelete">Kasować</text>
  <text id="ttDescription">Opis</text>
  <text id="ttDifficulty">Trudność</text>
  <text id="ttDifficultyQuestions">Pytania na poziom trudności</text>
  <text id="ttDistribution">Dystrybucja</text>
  <text id="ttDo">Zrób egzamin</text>
  <text id="ttDTAnswerInfo">Pokazuje _TOTAL_ odpowiedzi</text>
  <text id="ttDTAnswerFiltered">(przefiltrowane z odpowiedzi całkowitych _MAX_)</text>
  <text id="ttDTAnswerEmpty">Brak odpowiedzi do pokazania</text>
  <text id="ttDTExamInfo">Pokazywanie _TOTAL_ egzaminów w toku</text>
  <text id="ttDTExamFiltered">(odfiltrowane z łącznej liczby egzaminów _MAX_ w toku)</text>
  <text id="ttDTExamEmpty">Brak egzaminów do pokazania</text>
  <text id="ttDTQuestionInfo">Pokazuje _TOTAL_ pytania</text>
  <text id="ttDTQuestionFiltered">(przefiltrowane z pytań całkowitych _MAX_)</text>
  <text id="ttDTQuestionEmpty">Brak pytań do pokazania</text>
  <text id="ttDTRegisteredStudentInfo">Pokazywanie _TOTAL_ zarejestrowanych studentów</text>
  <text id="ttDTRegisteredStudentFiltered">(odfiltrowane z _MAX_ ogółem zarejestrowanych studentów)</text>
  <text id="ttDTRegisteredStudentEmpty">Brak zarejestrowanych studentów do pokazania</text>
  <text id="ttDTStudentsInfo">Pokazuje _TOTAL_ studentów</text>
  <text id="ttDTStudentsFiltered">(odfiltrowane z ogółu studentów _MAX_)</text>
  <text id="ttDTStudentsEmpty">Brak uczniów do pokazania</text>
  <text id="ttDTTestInfo">Pokazuje test _TOTAL_</text>
  <text id="ttDTTeacherInfo">Pokazuje _TOTAL_ nauczycieli</text>
  <text id="ttDTTeacherFiltered">(odfiltrowane z nauczycieli ogółem _MAX_)</text>
  <text id="ttDTTeacherEmpty">Brak nauczyciela do pokazania</text>
  <text id="ttDTTestFiltered">(przefiltrowane z testów ogółem _MAX_)</text>
  <text id="ttDTTestEmpty">Brak testów do pokazania</text>
  <text id="ttDone">Egzamin wykonany</text>
  <text id="ttDuration">Trwanie</text>
  <text id="ttDTsubquestionInfo">Sub pytania</text>
  <!-- ======================== E ======================== -->
  <text id="ttEdit">Edytować</text>
  <text id="ttEditableScore">Wynik do edycji</text>
  <text id="ttError">Błąd</text>
  <text id="ttEmail">E-mail</text>
  <text id="ttEnd">Koniec</text>
  <text id="ttEverywhere">Wszędzie</text>
  <text id="ttExam">Egzamin</text>
  <text id="ttExams">Egzaminy</text>
  <text id="ttExit">Wyjście</text>
  <text id="ttExtra">Dodatkowy</text>
  <text id="ttExamsArchive">Archiwum</text>
  <text id="ttExamsInProgress">Egzaminy w toku</text>
  <text id="ttETeachers">Egzaminator</text>
  <text id="ttErrorquestion">Zgłoś błąd</text>
  <!-- ===================== ERRORS ====================== -->
  <text id="ttEActivationFails">Aktywacja kończy się niepowodzeniem!</text>
  <text id="ttEAlreadyRegistered">Student jest już zarejestrowany na ten egzamin!</text>
  <text id="ttEAnswerInSet">Operacja nie może zostać zakończona.</text>
  <text id="ttEAnswerNotFound">Nie znaleziono odpowiedzi</text>
  <text id="ttEAnswers">Wystąpił problem z odpowiedziami.</text>
  <text id="ttEDatabase">Błąd bazy danych!</text>
  <text id="ttEDates">Daty są nieprawidłowe!</text>
  <text id="ttEEditRoomAll">Nie można edytować pokoju „All”!</text>
  <text id="ttEEmailAlreadyRegistered">Email już zarejestrowany!</text>
  <text id="ttEEmailNotRegistered">E-mail nie jest zarejestrowany!</text>
  <text id="ttEEmailNotValid">Wpisany e-mail jest nieprawidłowy!</text>
  <text id="ttEEmailsNotMatch">Dwa e-maile się nie zgadzają!</text>
  <text id="ttEEmptyFields">Jedno lub więcej pól jest pustych!</text>
  <text id="ttEExamArchived">Operacja nie może zostać zakończona.</text>
  <text id="ttEExamNotFound">Nie znaleziono egzaminu!</text>
  <text id="ttEExamNotStarted">Nie możesz rozpocząć egzaminu.</text>
  <text id="ttEExamStarted">Operacja nie może zostać zakończona, ponieważ egzamin już się rozpoczął!</text>
  <text id="ttEExamWaiting">Operacja nie może zostać zakończona, ponieważ egzamin nigdy się nie rozpoczął!</text>
  <text id="ttEExamsNotArchivedDeleteTopic">Operacja nie może zostać zakończona, ponieważ co najmniej jeden nie zarchiwizowany egzamin zawiera pytania z tego tematu!</text>
  <text id="ttEExamsNotArchivedEditTestSettings">Operacja nie może zostać zakończona, ponieważ te ustawienia są używane przez co najmniej jeden niezarchiwizowany egzamin.</text>
  <text id="ttEExamsNotArchivedDeleteTestSettings">Operacja nie może zostać zakończona, ponieważ te ustawienia są używane przez co najmniej jeden nie zarchiwizowany egzamin!</text>
  <text id="ttEIncorrectField">Jedno lub więcej pól jest niepoprawnych!</text>
  <text id="ttELogin">E-mail i / lub hasło są nieprawidłowe!</text>
  <text id="ttEMainLanguageEmpty">Główny język tematu nie może być pusty!</text>
  <text id="ttEMandatoryQuestion">Jest to obowiązkowe pytanie dotyczące ustawienia testu „_TESTSETTING_”: nie można go usunąć ani edytować jego trudności lub tematu.</text>
  <text id="ttENotAuthorized">Twój klient nie jest autoryzowany.</text>
  <text id="ttENoStudentsToRegister">Żaden student nie może się zarejestrować!</text>
  <text id="ttENoTopicsForSubject">Brak tematu na ten temat!</text>
  <text id="ttEOldPasswordWrong">Stare hasło jest nieprawidłowe!</text>
  <text id="ttEPassword">Złe hasło!</text>
  <text id="ttEPasswordShort">Hasło jest za krótkie.</text>
  <text id="ttEPasswordsNotMatch">Dwa hasła nie pasują!</text>
  <text id="ttEQuestAnswPicker">Błąd podczas wybierania pytań i odpowiedzi.</text>
  <text id="ttEQuestionInSet">Operacja nie może zostać zakończona.</text>
  <text id="ttEQuestionNotFound">Nie znaleziono pytania!</text>
  <text id="ttEQuestionType">Nieprawidłowy typ pytania!</text>
  <text id="ttERegFailedQuestions">Rejestracja nie powiodła się: zbyt mało pytań!</text>
  <text id="ttERoomAllDelete">Nie można usunąć pokoju „All”!</text>
  <text id="ttERoomUsed">Operacja nie może zostać zakończona.</text>
  <text id="ttESaveBeforeNew">Przed utworzeniem nowego przedmiotu zapisz lub anuluj już utworzony.</text>
  <text id="ttESelectQuestionType">Musisz wybrać jeden z dostępnych typów pytań!</text>
  <text id="ttESelectSubject">Musisz wybrać jeden ze swoich przedmiotów!</text>
  <text id="ttESelectTestSettings">Musisz wybrać jedno z ustawień testowych!</text>
  <text id="ttESetNotFound">Nie znaleziono zestawu pytań!</text>
  <text id="ttETestAlreadyArchived">Operacja nie może zostać zakończona.</text>
  <text id="ttETestAlreadySubmitted">Operacja nie może zostać zakończona.</text>
  <text id="ttETestBlockedSubmitted">Operacja nie może zostać zakończona.</text>
  <text id="ttETestNotArchived">Operacja nie może zostać zakończona.</text>
  <text id="ttETestNotFound">Nie znaleziono testu!</text>
  <text id="ttETestsNotArchived">Niektóre testy nie zostały zarchiwizowane!</text>
  <text id="ttETestSettingDeleteQuestion">Operacja nie może zostać zakończona.</text>
  <text id="ttETestSettingDeleteTopic">Operacja nie może zostać zakończona.</text>
  <text id="ttETimeExpired">Dostępny czas upłynął!</text>
  <text id="ttETranslationExists">Tłumaczenie wybranego języka już istnieje!</text>
  <text id="ttEUserNotFound">Użytkownik nie znaleziony!</text>
  <text id="ttEValues">Niektóre wartości są nieprawidłowe!</text>
  <!-- ======================== F ======================== -->
  <text id="ttFalse">Fałszywy</text>
  <text id="ttFinalScore">Wynik końcowy</text>
  <!-- ======================== G ======================== -->
  <text id="ttGeneralInformations">Informacje ogólne</text>
  <!-- ======================== H ======================== -->
  <text id="ttHours">godziny</text>
  <text id="ttHome">Dom</text>
  <text id="ttHomepage">Strona główna</text>
  <text id="ttHost">Gospodarz</text>
  <!-- ======================= HELP ====================== -->
  <text id="ttHAnswPanel">Kliknij dwukrotnie, aby edytować wybraną odpowiedź</text>
  <text id="ttHQuestLanguagesPanel">Kliknij, aby pokazać tłumaczenie wybranego pytania</text>
  <text id="ttHQuestPanel">Jedno kliknięcie umożliwia wybranie i wyświetlenie podglądu pytania oraz dwukrotne kliknięcie w celu edycji pytania i udzielenia odpowiedzi.</text>
  <text id="ttHQuestPreviewPanel">Odpowiedzi z pomarańczowym tłem nie są tłumaczone na żądany język</text>
  <text id="ttHQuestTopicPanel">Pojedyncze kliknięcie, aby filtrować pytania i podwójnie kliknąć, aby edytować informacje o temacie</text>
  <!-- ======================== I ======================== -->
  <text id="ttInfo">Informacje</text>
  <text id="ttIPEnd">Koniec IPv4</text>
  <text id="ttIPStart">IPv4 Start</text>
  <text id="ttInactive">Nieaktywny</text>
  <text id="ttImportQM">Import</text>
  <text id="ttImport">Importuj QM</text>
  <text id="ttImportComplete">Import zakończony pomyślnie</text>
  <!-- ======================== J ======================== -->
  <text id="ttJoin">Przystąpić</text>
  <!-- ======================== K ======================== -->
  <!-- ======================== L ======================== -->
  <text id="ttLanguage">Język</text>
  <text id="ttLanguages">Języki</text>
  <text id="ttLogin">Zaloguj Się</text>
  <text id="ttLogo">Logo</text>
  <text id="ttLoginOk">Logowanie zakończone!</text>
  <text id="ttLogout">WYLOGUJ</text>
  <!-- ======================== M ======================== -->
  <text id="ttMailLostPassword">Aby zresetować hasło do konta, kliknij poniższy link: _LINK_ Jeśli nie zażądałeś zresetowania hasła, zignoruj ​​ten e-mail.</text>
  <text id="ttMailCredentials">Drogi _USERNAME_, Twoje hasło powiązane z kontem _USEREMAIL_ zostało zmodyfikowane zgodnie z twoją prośbą.</text>
  <text id="ttMailNewTeacher">Witaj w _SYSTEMNAME_.</text>
  <text id="ttMainLanguage">Główny język</text>
  <text id="ttManage">Zarządzanie</text>
  <text id="ttMandatory">Obowiązkowy</text>
  <text id="ttManual">podręcznik</text>
  <text id="ttMinutes">minuty</text>
  <text id="ttMyExams">Moje egzaminy</text>
  <text id="ttMySettings">Moje ustawienia</text>
  <text id="ttMySubjects">Wybierz temat</text>
  <!-- ==================== MESSAGES ===================== -->
  <text id="ttMActivation">Hasło zostało pomyślnie ustawione.</text>
  <text id="ttMAnswerDeleted">Odpowiedź została pomyślnie usunięta</text>
  <text id="ttMConfigurationsUpdated">Konfiguracja systemu została pomyślnie zaktualizowana</text>
  <text id="ttMConfirm">Test został pomyślnie potwierdzony i zarchiwizowany</text>
  <text id="ttMUserCreated">Tworzenie zakończone: wysłano do Ciebie wiadomość e-mail, aby dokończyć rejestrację.</text>
  <text id="ttMEdit">Zmiany zostały pomyślnie zapisane</text>
  <text id="ttMExamArchived">Egzamin pomyślnie zarchiwizowany</text>
  <text id="ttMExamDeleted">Egzamin został pomyślnie usunięty</text>
  <text id="ttMExamStarted">Egzamin został pomyślnie rozpoczęty</text>
  <text id="ttMExamStopped">Egzamin został pomyślnie zatrzymany</text>
  <text id="ttMLanguageCreated">Tłumaczenie zostało pomyślnie utworzone</text>
  <text id="ttMLanguageSaved">Tłumaczenie zostało pomyślnie zapisane</text>
  <text id="ttMLanguageUpdated">Tłumaczenie zostało pomyślnie zaktualizowane</text>
  <text id="ttMNewAnswer">Odpowiedź została pomyślnie utworzona</text>
  <text id="ttMNewQuestion">Pytanie zostało pomyślnie utworzone</text>
  <text id="ttMNewRoom">Pomyślnie utworzono pokój</text>
  <text id="ttMNewSettings">Pomyślnie utworzono ustawienia testowe</text>
  <text id="ttMNewSubject">Temat pomyślnie utworzony</text>
  <text id="ttMNewTopic">Temat pomyślnie utworzony</text>
  <text id="ttMPasswordRenewed">Hasło egzaminu zostało pomyślnie odnowione</text>
  <text id="ttMQuestionDeleted">Pytanie zostało pomyślnie usunięte</text>
  <text id="ttMRegistration">Udało Ci się zarejestrować na tym egzaminie</text>
  <text id="ttMResetConfirmed">Żądanie zakończone: wysłano wiadomość e-mail, aby zresetować hasło.</text>
  <text id="ttMRoomDeleted">Pokój został pomyślnie usunięty</text>
  <text id="ttMSelectLanguage">Wybierz język, którym chcesz zarządzać</text>
  <text id="ttMSettingsDeleted">Testowe ustawienia zostały pomyślnie usunięte</text>
  <text id="ttMStudentsRegistered">Studenci pomyślnie zarejestrowali się na egzaminie</text>
  <text id="ttMSubjectDeleted">Temat został pomyślnie usunięty</text>
  <text id="ttMSubjectQuestions">Aby zarządzać tematami i pytaniami, wybierz temat</text>
  <text id="ttMSubjectSettings">Aby zarządzać ustawieniami egzaminu, wybierz temat</text>
  <text id="ttMTestBlocked">Test został pomyślnie zablokowany</text>
  <text id="ttMTestSubmitted">Test został pomyślnie przesłany</text>
  <text id="ttMTestUnblocked">Przetestuj pomyślnie odblokowany</text>
  <text id="ttMTopicDeleted">Temat został pomyślnie usunięty</text>
  <!-- ======================== N ======================== -->
  <text id="ttName">Imię</text>
  <text id="ttNumberError">Wartość powinna być liczbą całkowitą lub dziesiętną (ES: 12,5)</text>
  <text id="ttNegativeScores">Wyniki negatywne</text>
  <text id="ttNew">Nowy</text>
  <text id="ttNext">Kolejny</text>
  <text id="ttNewAnswer">Nowa odpowiedź</text>
  <text id="ttNewCredentials">Nowe poświadczenia</text>
  <text id="ttNewLanguage">Nowy język</text>
  <text id="ttNewPassword">nowe hasło</text>
  <text id="ttNewQuestion">Nowe pytanie</text>
  <text id="ttNewRegistration">Nowa rejestracja</text>
  <text id="ttNewRoom">Nowy pokój</text>
  <text id="ttNewTeacher">Nowy nauczyciel</text>
  <text id="ttNewTestSettings">Nowe ustawienia</text>
  <text id="ttNewSubject">Nowy przedmiot</text>
  <text id="ttNewStudent">Nowy uczeń</text>
  <text id="ttNewTopic">Nowy temat</text>
  <text id="ttNewUser">Nowy użytkownik</text>
  <text id="ttNo">Nie</text>
  <text id="ttNoAnswers">Brak odpowiedzi na to pytanie</text>
  <text id="ttNoExams">Brak dostępnych egzaminów dla tego przedmiotu</text>
  <text id="ttNoExamInProgress">Brak egzaminu w toku</text>
  <text id="ttNoInfo">Nie ma informacji o tym egzaminie</text>
  <text id="ttNoQuestions">Brak dostępnych pytań na ten temat</text>
  <text id="ttNoRooms">Nie utworzono pokoi: dostępne tylko „Wszystkie”</text>
  <text id="ttNoSettings">Brak ustawień dla tego tematu</text>
  <text id="ttNoSubjects">Brak dostępnych tematów</text>
  <text id="ttNoTestToCorrect">Brak testów do poprawienia</text>
  <text id="ttNoUserRegistered">Brak zarejestrowanych użytkowników do tego egzaminu</text>
  <!-- ======================== O ======================== -->
  <text id="ttOldPassword">Stare hasło</text>
  <text id="ttEssayQuestion">Pytanie esejowe</text>
  <!-- ======================== P ======================== -->
  <text id="ttPassword">Hasło</text>
  <text id="ttPasswordLost">Zgubiłeś hasło?</text>
  <text id="ttPort">Port</text>
  <text id="ttProfile">Profil</text>
  <text id="ttPrepareImportQM">Zapowiedź</text>
  <!-- ======================== Q ======================== -->
  <text id="ttQuestion">Pytanie</text>
  <text id="ttQuestionPreview">Podgląd pytania</text>
  <text id="ttQuestions">pytania</text>
  <text id="ttQEc">Kalkulator</text>
  <text id="ttQEp">Układ okresowy</text>
  <text id="ttQTMC">Wielokrotny wybór</text>
  <text id="ttQTMCDescription">W pytaniu wielokrotnego wyboru uczestnik wybiera jeden wybór spośród wielu opcji, aby odpowiedzieć na pytanie.</text>
  <text id="ttQTMR">Odpowiedź wielokrotna</text>
  <text id="ttQTMRDescription">Pytanie z wieloma odpowiedziami jest jak wielokrotny wybór, z tym wyjątkiem, że zamiast wymagać od siebie co najwyżej jednego wyboru, użytkownik może dokonać jednego lub więcej niż jednego wyboru.</text>
  <text id="ttQTES">Esej Pytanie</text>
  <text id="ttQTESDescription">Pytanie esej pozwala uczestnikowi wprowadzić długą, swobodną odpowiedź tekstową na pytanie.</text>
  <text id="ttQTYN">Tak nie</text>
  <text id="ttQTYNDescription">Pytanie Tak / Nie jest pytaniem wielokrotnego wyboru, które prosi uczestnika o udzielenie odpowiedzi „Tak” lub „Nie” na pytanie.</text>
  <text id="ttQTTF">Prawda fałsz</text>
  <text id="ttQTTFDescription">Pytanie Prawda / Fałsz to pytanie wielokrotnego wyboru, które prosi uczestnika o udzielenie odpowiedzi „prawda” lub „fałsz” na pytanie.</text>
  <text id="ttQTNM">Numeryczny</text>
  <text id="ttQTNMDescription">W pytaniu numerycznym uczestnik odpowiada, wpisując liczbę całkowitą lub liczbę rzeczywistą.</text>
  <text id="ttQTTM">Dopasowanie tekstu</text>
  <text id="ttQTTMDescription">W pytaniu Dopasowanie tekstu uczestnik wpisuje jedno słowo lub kilka słów, aby wskazać swoją odpowiedź.</text>
  <text id="ttQTHS">Hotspot</text>
  <text id="ttQTHSDescription">Pytanie Hotspot to pytanie typu „przeciągnij i upuść” zawierające tylko jeden właściwy obszar.</text>
  <text id="ttQTPL">Pull Down List</text>
  <text id="ttQuesionid">Identyfikator pytania</text>
  <text id="ttQuestionNotes">Opis</text>
  <text id="ttQuestionsend">Wyślij raport</text>
  <text id="ttQuestionreporting">Aby zgłosić więcej pytań, musisz pozostawić pole id puste</text>
  <!-- ======================== R ======================== -->
  <text id="ttRandom">Losowy</text>
  <text id="ttRefresh">Odświeżać</text>
  <text id="ttRegister">Zarejestrować</text>
  <text id="ttRegistrations">Rejestracje</text>
  <text id="ttRegEnd">Zamknięcie rejestracji</text>
  <text id="ttRenewPassword">Odnów hasło</text>
  <text id="ttReset">Nastawić</text>
  <text id="ttResetPassword">Zresetuj hasło</text>
  <text id="ttRole">Rola</text>
  <text id="ttRooms">Pokoje</text>
  <!-- ======================== S ======================== -->
  <text id="ttSave">Zapisać</text>
  <text id="ttSaveAnswerInfo">Zapisz informacje o odpowiedzi</text>
  <text id="ttSaveLanguageFiles">Zapisz pliki językowe</text>
  <text id="ttSaveLanguageXML">Zapisz pliki językowe XML</text>
  <text id="ttSaveQuestionInfo">Zapisz informacje o pytaniu</text>
  <text id="ttScore">Wynik</text>
  <text id="ttScoreFinal">Wynik końcowy</text>
  <text id="ttScoreTest">Wynik testu</text>
  <text id="ttScoreType">Rodzaj wyniku</text>
  <text id="ttScoreMin">Minimalny wynik</text>
  <text id="ttSelectSubject">Wybierz Temat</text>
  <text id="ttSelectSubjectBefore">Wybierz temat wcześniej</text>
  <text id="ttSet">Zestaw</text>
  <text id="ttSetPassword">Ustaw swoje hasło</text>
  <text id="ttSettings">Ustawienia</text>
  <text id="ttShowHide">Pokaż ukryj</text>
  <text id="ttSelectSubQuestion">Wybierz pytanie</text>
  <text id="ttSkin">Skóra</text>
  <text id="ttStart">Początek</text>
  <text id="ttStarted">Zaczęło się</text>
  <text id="ttStop">Zatrzymać</text>
  <text id="ttStopped">Zatrzymany</text>
  <text id="ttStartTest">Rozpocznij test</text>
  <text id="ttStatus">Status</text>
  <text id="ttStats">Statystyki</text>
  <text id="ttStudent">Student</text>
  <text id="ttStudents">Uczniowie</text>
  <text id="ttST10">Dziesiąte</text>
  <text id="ttST30">Trzydzieste</text>
  <text id="ttST100">Setny</text>
  <text id="ttSubject">Przedmiot</text>
  <text id="ttSubjects">Przedmioty</text>
  <text id="ttSubmit">Zatwierdź</text>
  <text id="ttSurname">Nazwisko</text>
  <text id="ttSystem">System</text>
  <text id="ttSystemConfiguration">Konfiguracja systemu</text>
  <text id="ttSbjVers">Wersja</text>
  <!-- ======================== T ======================== -->
  <text id="ttTeacher">Nauczyciel</text>
  <text id="ttTeachers">Nauczyciele</text>
  <text id="ttTest">Test</text>
  <text id="ttTests">Testy</text>
  <text id="ttTestToCorrect">Testy do poprawienia</text>
  <text id="ttText">Tekst</text>
  <text id="ttTime">Czas</text>
  <text id="ttTimeEnd">Koniec czasu</text>
  <text id="ttTimeStart">Czas rozpoczęcia</text>
  <text id="ttTimeUsed">Wykorzystany czas</text>
  <text id="ttTimeZone">Strefa czasowa</text>
  <text id="ttTitle">Tytuł</text>
  <text id="ttTopic">Temat</text>
  <text id="ttTopics">Tematy</text>
  <text id="ttTopicsAndQuestions">Tematy i pytania</text>
  <text id="ttTopicsQuestions">Pytania na tematy</text>
  <text id="ttTranslations">Tłumaczenia</text>
  <text id="ttTrue">Prawdziwe</text>
  <text id="ttType">Rodzaj</text>
  <!-- ======================== U ======================== -->
  <text id="ttUser">Użytkownik</text>
  <text id="ttUsers">Użytkownicy</text>
  <!-- ======================== V ======================== -->
  <text id="ttView">Widok</text>
  <!-- ======================== W ======================== -->
  <text id="ttWelcome">Witamy</text>
  <text id="ttWaiting">Czekanie</text>
  <text id="ttWarning">Ostrzeżenie</text>
  <!-- ======================== X ======================== -->
  <!-- ======================== Y ======================== -->
  <text id="ttYes">tak</text>
  <!-- ======================== Z ======================== -->
  <text id="ttAssesmentOverview">Raport z przeglądu oceny</text>
  <text id="ttDeselectAll">Odznacz wszystkie</text>
  <text id="ttErrorUserParameter">Wybierz szczegół uczestnika, aby kontynuować!</text>
  <text id="ttQuestionerror">Identyfikator pytania</text>
  <text id="ttRemove">Usunąć</text>
  <text id="ttReportCoachingError">Wybierz ocenę i kontynuuj uczestnika</text>
  <text id="ttReportCoachingError2">Wybierz ocenę, aby kontynuować</text>
  <text id="ttReportErrorStudent">Wybrany student nie brał udziału w wybranych testach</text>
  <text id="ttReportMainAO">Główny</text>
  <text id="ttReportTemplateDeleteFailed">Usuwanie nie powiodło się</text>
  <text id="ttReportTemplateDelet">Szablon usunięty</text>
  <text id="ttReportTemplateLoaded">Szablon caricato correttamente</text>
  <text id="ttReportTemplateSaveError">Wstaw nazwę szablonu bez spacji!</text>
  <text id="ttReportTemplateSaved">Szablon zapisany poprawnie</text>
  <text id="ttReportTemplateDuplicateError">Nazwa szablonu już istnieje!</text>
  <text id="ttReportScoreFilter">Jeśli wybrałeś już uczestnika, teraz wybierz go ponownie</text>
  <text id="ttSelectAll">Zaznacz wszystko</text>
  <text id="ttQTFB">Wypełnij puste miejsca</text>
  <text id="ttQTFB_TEXT">Wypełnij poniższy tekst odpowiednimi słowami</text>
  <text id="ttQTFBDescription">W wypełnieniu pustych pól uczestnik musi wypełnić tekst poprawną odpowiedzią w polu tekstowym</text>
  <text id="ttPosterImageVideo">Ładowanie logo</text>
  <text id="ttWidthVideo">Szerokość</text>
  <text id="ttHeightVideo">Wysokość</text>
  <text id="ttIdVideo">Kod identyfikacyjny</text>
  <text id="ttVideoTypeVideo">Format wideo</text>
  <text id="ttNumberOfPlaysVideo">Maksymalna liczba odtworzeń</text>
  <text id="ttToolbarVideo">Wideo</text>
  <text id="ttDialogTitleVideo">Właściwość wideo</text>
  <text id="ttFakeObjectVideo">Wideo</text>
  <text id="ttPropertiesVideo">Edytuj wideo</text>
  <text id="ttWidthRequiredVideo">Szerokość powinna być ustawiona</text>
  <text id="ttHeightRequiredVideo">Wysokość należy ustawić</text>
  <text id="ttNumberOfPlayRequiredVideo">Należy ustawić maksymalną liczbę odtworzeń</text>
  <text id="ttFallbackTemplateVideo">Twoja przeglądarka nie obsługuje wideo HTML5</text>
  <text id="ttBrowseVideo">Przeglądaj serwer</text>
  <text id="ttsourceVideo">Źródło wideo</text>
  <text id="ttNumberOfPlayAlertVideo">Osiągnąłeś maksymalną liczbę odtwarzanych filmów</text>
  <text id="ttHelpDefault">Panel informacyjny</text>
  <text id="ttHelpDefaultDescription">Naciśnij ten przycisk, aby uzyskać opis tego, co możesz zrobić</text>
  <text id="ttHelpQuestion">Wybierz pytanie, aby przeczytać jego zawartość lub kliknij dwukrotnie, aby edytować</text>
  <text id="ttHelpADMINNewTeacherDescription">Zdefiniuj konto nowego administratora, nauczyciela lub egzaminatora</text>
  <text id="ttHelpADMINNewStudentDescription">Zdefiniuj konto nowego ucznia</text>
  <text id="ttHelpADMINSelLanguageDescription">Wybierz język do zarządzania</text>
  <text id="ttHelpADMINLanguageDescription">Tutaj możesz zmienić lokalizacje słów używanych przez system</text>
  <text id="ttHelpADMINSystemConf">Tutaj możesz zmienić ustawienia EOL, bądź ostrożny</text>
  <text id="ttHelpADMINRoom">Zdefiniuj pomieszczenia, w których będą przeprowadzane testy</text>
  <text id="ttHelpADMINImport">This screen allows you to import new questions to Question Mark</text>
  <text id="ttHelpADMINProfile">This screen allows you to edit your profile</text>
  <text id="ttHelpReportAreport">Ten ekran umożliwia utworzenie Areportu, obowiązkowe jest wybranie co najmniej jednego przedmiotu</text>
  <text id="ttHelpReportAreportTemplate">Wybierz, jakie informacje możesz uzyskać w raporcie</text>
  <text id="ttHelpReportCreport">Ten ekran pozwala utworzyć Creport, obowiązkowe jest wybranie uczestnika</text>
  <text id="ttHelpReportCreportlist">Wybierz egzamin, aby utworzyć raport</text>
  <text id="ttHelpStudent">To the left are the available tests, to the right the selected examination details</text>
  <text id="ttHelpStudentTest">You are in the exam screen, answer the questions and submit the test</text>
  <text id="ttHelpAdminErrorQuestion">If you find problems you can report from this page.</text>
  <text id="ttHelpExamsCorrect">Tutaj otrzymasz egzamin wykonany przez studenta, sprawdź, czy poprawka została wykonana poprawnie, a następnie potwierdź głosowanie.</text>
  <text id="ttHelpExamsSettings">Na tym ekranie można zdefiniować lub zmienić ustawienia, które będą używane w przyszłych badaniach.</text>
  <text id="ttQTPLDescription">Lista rozwijana to pytanie zamknięte, które pozwala respondentom wybrać jeden wybór odpowiedzi z listy opcji przedstawionych w menu rozwijanym. Jeśli chcesz wyświetlić opcje odpowiedzi jako przyciski opcji lub pola wyboru, użyj pytania wielokrotnego wyboru</text>
  <text id="ttQuestionsubPL">Podpytania</text>
  <text id="ttHelpLog">Plik dziennika zostanie automatycznie utworzony po zmianie pytania już przypisanego do testu.</text>
  <text id="ttErrorSent">ACK</text>
  <text id="ttGroup">Grupa</text>
  <text id="ttSubgroup">Podgrupa</text>
  <text id="ttAOreportSaved">Cały wygenerowany raport zostanie zapisany na serwerze.</text>